//! Bulk operations for Bank entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBankDto;
use crate::application::service::BankService;
use crate::domain::entity::Bank;

/// Bulk operation handler for Bank entities.
///
/// Wraps `BankService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BankBulkService = GenericBulkService<Bank, CreateBankDto, BankService>;

// <<< CUSTOM
// END CUSTOM
