//! Bulk operations for DataSubjectRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDataSubjectRequestDto;
use crate::application::service::DataSubjectRequestService;
use crate::domain::entity::DataSubjectRequest;

/// Bulk operation handler for DataSubjectRequest entities.
///
/// Wraps `DataSubjectRequestService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DataSubjectRequestBulkService = GenericBulkService<DataSubjectRequest, CreateDataSubjectRequestDto, DataSubjectRequestService>;

// <<< CUSTOM
// END CUSTOM
