//! Bulk operations for EmploymentHistory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmploymentHistoryDto;
use crate::application::service::EmploymentHistoryService;
use crate::domain::entity::EmploymentHistory;

/// Bulk operation handler for EmploymentHistory entities.
///
/// Wraps `EmploymentHistoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmploymentHistoryBulkService = GenericBulkService<EmploymentHistory, CreateEmploymentHistoryDto, EmploymentHistoryService>;

// <<< CUSTOM
// END CUSTOM
