//! Bulk operations for EmployeeBpjs entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeBpjsDto;
use crate::application::service::EmployeeBpjsService;
use crate::domain::entity::EmployeeBpjs;

/// Bulk operation handler for EmployeeBpjs entities.
///
/// Wraps `EmployeeBpjsService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeBpjsBulkService = GenericBulkService<EmployeeBpjs, CreateEmployeeBpjsDto, EmployeeBpjsService>;

// <<< CUSTOM
// END CUSTOM
