//! Bulk operations for EmployeeWorkExperience entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeWorkExperienceDto;
use crate::application::service::EmployeeWorkExperienceService;
use crate::domain::entity::EmployeeWorkExperience;

/// Bulk operation handler for EmployeeWorkExperience entities.
///
/// Wraps `EmployeeWorkExperienceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeWorkExperienceBulkService = GenericBulkService<EmployeeWorkExperience, CreateEmployeeWorkExperienceDto, EmployeeWorkExperienceService>;

// <<< CUSTOM
// END CUSTOM
