//! Bulk operations for EmployeeCertification entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeCertificationDto;
use crate::application::service::EmployeeCertificationService;
use crate::domain::entity::EmployeeCertification;

/// Bulk operation handler for EmployeeCertification entities.
///
/// Wraps `EmployeeCertificationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeCertificationBulkService = GenericBulkService<EmployeeCertification, CreateEmployeeCertificationDto, EmployeeCertificationService>;

// <<< CUSTOM
// END CUSTOM
