//! Bulk operations for Example entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateExampleDto;
use crate::application::service::ExampleService;
use crate::domain::entity::Example;

/// Bulk operation handler for Example entities.
///
/// Wraps `ExampleService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ExampleBulkService = GenericBulkService<Example, CreateExampleDto, ExampleService>;

// <<< CUSTOM
// END CUSTOM
