//! Employee Module Routes
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides route composition with dual pattern support:
//! - Stateless routes: `create_stateless_routes()` -> `Router<()>`
//! - Stateful routes: `create_stateful_routes()` -> `Router<AppState>`

use axum::Router;
use std::sync::Arc;

// Import handlers
use crate::presentation::http::{
    create_bank_routes,
    create_bank_read_routes,
    create_data_consent_routes,
    create_data_consent_read_routes,
    create_data_subject_request_routes,
    create_data_subject_request_read_routes,
    create_employee_routes,
    create_employee_read_routes,
    create_employee_bank_account_routes,
    create_employee_bank_account_read_routes,
    create_employee_bpjs_routes,
    create_employee_bpjs_read_routes,
    create_employee_certification_routes,
    create_employee_certification_read_routes,
    create_employee_contact_routes,
    create_employee_contact_read_routes,
    create_employee_education_routes,
    create_employee_education_read_routes,
    create_employee_family_routes,
    create_employee_family_read_routes,
    create_employee_identity_routes,
    create_employee_identity_read_routes,
    create_employee_tax_routes,
    create_employee_tax_read_routes,
    create_employee_work_experience_routes,
    create_employee_work_experience_read_routes,
    create_employment_routes,
    create_employment_read_routes,
    create_employment_history_routes,
    create_employment_history_read_routes,
    create_pii_access_log_routes,
    create_pii_access_log_read_routes,
    create_religion_routes,
    create_religion_read_routes
};

// Import AppState for stateful routes
use crate::handlers::AppState;

// ============================================================
// PATTERN 1: STATELESS ROUTES
// ============================================================

/// Create stateless routes for the Employee module.
///
/// These routes don't require shared state and are simpler to use.
/// Use this when you only need standard CRUD operations.
///
/// # Example
///
/// ```ignore
/// let module = EmployeeModule::builder().with_database(pool).build()?;
/// let routes = create_stateless_routes(&module);
/// let app = Router::new().merge(routes);
/// ```
pub fn create_stateless_routes(module: &crate::EmployeeModule) -> Router<()> {
    Router::new()
        .merge(create_bank_routes(module.bank_service.clone()))
        .merge(create_data_consent_routes(module.data_consent_service.clone()))
        .merge(create_data_subject_request_routes(module.data_subject_request_service.clone()))
        .merge(create_employee_routes(module.employee_service.clone()))
        .merge(create_employee_bank_account_routes(module.employee_bank_account_service.clone()))
        .merge(create_employee_bpjs_routes(module.employee_bpjs_service.clone()))
        .merge(create_employee_certification_routes(module.employee_certification_service.clone()))
        .merge(create_employee_contact_routes(module.employee_contact_service.clone()))
        .merge(create_employee_education_routes(module.employee_education_service.clone()))
        .merge(create_employee_family_routes(module.employee_family_service.clone()))
        .merge(create_employee_identity_routes(module.employee_identity_service.clone()))
        .merge(create_employee_tax_routes(module.employee_tax_service.clone()))
        .merge(create_employee_work_experience_routes(module.employee_work_experience_service.clone()))
        .merge(create_employment_routes(module.employment_service.clone()))
        .merge(create_employment_history_routes(module.employment_history_service.clone()))
        .merge(create_pii_access_log_routes(module.pii_access_log_service.clone()))
        .merge(create_religion_routes(module.religion_service.clone()))
}

/// Read-only routes for the Employee module — every entity mounted READ-ONLY (the guarded base).
///
/// The generic `create_stateless_routes` exposes full mutable CRUD with no domain
/// validation; this exposes only reads, so generic mutation can't bypass a write
/// service's invariants. Extend it: `create_readonly_employee_routes(m).merge(my_validated_writes)`.
pub fn create_readonly_employee_routes(module: &crate::EmployeeModule) -> Router<()> {
    Router::new()
        .merge(create_bank_read_routes(module.bank_service.clone()))
        .merge(create_data_consent_read_routes(module.data_consent_service.clone()))
        .merge(create_data_subject_request_read_routes(module.data_subject_request_service.clone()))
        .merge(create_employee_read_routes(module.employee_service.clone()))
        .merge(create_employee_bank_account_read_routes(module.employee_bank_account_service.clone()))
        .merge(create_employee_bpjs_read_routes(module.employee_bpjs_service.clone()))
        .merge(create_employee_certification_read_routes(module.employee_certification_service.clone()))
        .merge(create_employee_contact_read_routes(module.employee_contact_service.clone()))
        .merge(create_employee_education_read_routes(module.employee_education_service.clone()))
        .merge(create_employee_family_read_routes(module.employee_family_service.clone()))
        .merge(create_employee_identity_read_routes(module.employee_identity_service.clone()))
        .merge(create_employee_tax_read_routes(module.employee_tax_service.clone()))
        .merge(create_employee_work_experience_read_routes(module.employee_work_experience_service.clone()))
        .merge(create_employment_read_routes(module.employment_service.clone()))
        .merge(create_employment_history_read_routes(module.employment_history_service.clone()))
        .merge(create_pii_access_log_read_routes(module.pii_access_log_service.clone()))
        .merge(create_religion_read_routes(module.religion_service.clone()))
}

/// Get all routes (stateless) for the Employee module.
///
/// This is a convenience function that wraps routes with API versioning.
pub fn get_routes(module: &crate::EmployeeModule) -> Router<()> {
    Router::new()
        .nest("/api/v1", create_stateless_routes(module))
}

// ============================================================
// PATTERN 2: STATEFUL ROUTES (WITH APPSTATE)
// ============================================================

/// Create stateful routes for the Employee module.
///
/// These routes require AppState and support custom handlers
/// that need access to services via dependency injection.
///
/// # Example
///
/// ```ignore
/// let module = EmployeeModule::builder().with_database(pool).build()?;
/// let state = AppState::from_module(&module);
/// let routes = create_stateful_routes();
/// let app = Router::new().merge(routes).with_state(state);
/// ```
pub fn create_stateful_routes() -> Router<AppState> {
    Router::new()
        // Add custom handlers here that need AppState
        // .route("/custom", get(custom_handler))
}

/// Create combined routes (stateless CRUD + stateful custom handlers).
///
/// This merges both stateless CRUD routes and stateful custom routes.
pub fn create_combined_routes(module: &crate::EmployeeModule) -> Router<AppState> {
    // First create stateless routes
    let crud_routes: Router<()> = create_stateless_routes(module);

    // Convert to stateful by adding state requirement
    // Note: The CRUD routes don't actually use the state,
    // but this allows them to be merged with stateful routes.
    let crud_routes_stateful: Router<AppState> = crud_routes.with_state(()).into();

    // Merge with stateful routes
    Router::new()
        .merge(crud_routes_stateful)
        .merge(create_stateful_routes())
}

/// Get all routes (stateful) for the Employee module.
///
/// This is a convenience function that wraps routes with API versioning.
pub fn get_routes_with_state(module: &crate::EmployeeModule) -> Router<AppState> {
    Router::new()
        .nest("/api/v1", create_combined_routes(module))
}

// ============================================================
// CUSTOM HANDLERS
// ============================================================

// <<< CUSTOM HANDLERS START >>>
// The hr.employee.public port (Wave 1 P1, H-1): the read-only peer directory, mounted
// beside the generated read surface. `create_readonly_employee_routes` stays generated —
// this wrapper is the guarded-composition convenience that composes both.
pub fn create_readonly_employee_routes_with_public(module: &crate::EmployeeModule) -> Router<()> {
    create_readonly_employee_routes(module)
        .merge(crate::presentation::http::create_employee_public_read_routes(
            module.db_pool.clone(),
        ))
}
// <<< CUSTOM HANDLERS END >>>
