//! DataConsent DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DataConsent;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DataCategory;
use crate::domain::entity::LawfulBasis;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DataConsent
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDataConsentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "data_category")]
    pub data_category: DataCategory,
    #[serde(alias = "lawful_basis")]
    pub lawful_basis: LawfulBasis,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "consent_given_at")]
    pub consent_given_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "consent_method")]
    pub consent_method: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "privacy_notice_version")]
    pub privacy_notice_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "retention_until")]
    pub retention_until: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "withdrawn_at")]
    pub withdrawn_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DataConsent
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDataConsentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "data_category")]
    pub data_category: DataCategory,
    #[serde(alias = "lawful_basis")]
    pub lawful_basis: LawfulBasis,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "consent_given_at")]
    pub consent_given_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "consent_method")]
    pub consent_method: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "privacy_notice_version")]
    pub privacy_notice_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "retention_until")]
    pub retention_until: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "withdrawn_at")]
    pub withdrawn_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DataConsent
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDataConsentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "data_category")]
    pub data_category: Option<DataCategory>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "lawful_basis")]
    pub lawful_basis: Option<LawfulBasis>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "consent_given_at")]
    pub consent_given_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "consent_method")]
    pub consent_method: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "privacy_notice_version")]
    pub privacy_notice_version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "retention_until")]
    pub retention_until: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "withdrawn_at")]
    pub withdrawn_at: Option<DateTime<Utc>>,
}

impl PatchDataConsentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.data_category.is_some() || self.lawful_basis.is_some() || self.consent_given_at.is_some() || self.consent_method.is_some() || self.privacy_notice_version.is_some() || self.retention_until.is_some() || self.withdrawn_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DataConsent entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DataConsentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub data_category: DataCategory,
    pub lawful_basis: LawfulBasis,
    pub consent_given_at: Option<DateTime<Utc>>,
    pub consent_method: Option<String>,
    pub privacy_notice_version: Option<String>,
    pub retention_until: Option<NaiveDate>,
    pub withdrawn_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DataConsent entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DataConsentListResponseDto {
    /// List of items
    pub items: Vec<DataConsentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DataConsentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DataConsentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DataConsentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub data_category: DataCategory,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DataConsent> for DataConsentResponseDto {
    fn from(entity: DataConsent) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            data_category: entity.data_category,
            lawful_basis: entity.lawful_basis,
            consent_given_at: entity.consent_given_at,
            consent_method: entity.consent_method,
            privacy_notice_version: entity.privacy_notice_version,
            retention_until: entity.retention_until,
            withdrawn_at: entity.withdrawn_at,
            metadata: entity.metadata,
        }
    }
}

impl From<DataConsent> for DataConsentSummaryDto {
    fn from(entity: DataConsent) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            data_category: entity.data_category,
            created_at,
        }
    }
}

impl From<CreateDataConsentDto> for DataConsent {
    fn from(dto: CreateDataConsentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            data_category: dto.data_category,
            lawful_basis: dto.lawful_basis,
            consent_given_at: dto.consent_given_at,
            consent_method: dto.consent_method,
            privacy_notice_version: dto.privacy_notice_version,
            retention_until: dto.retention_until,
            withdrawn_at: dto.withdrawn_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DataConsent> for DataConsentResponseDto {
    fn from(entity: &DataConsent) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            data_category: entity.data_category.clone(),
            lawful_basis: entity.lawful_basis.clone(),
            consent_given_at: entity.consent_given_at.clone(),
            consent_method: entity.consent_method.clone(),
            privacy_notice_version: entity.privacy_notice_version.clone(),
            retention_until: entity.retention_until.clone(),
            withdrawn_at: entity.withdrawn_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDataConsentDto> for DataConsent {
    fn from_create_dto(dto: CreateDataConsentDto) -> backbone_core::ServiceResult<Self> {
        Ok(DataConsent::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDataConsentDto> for DataConsent {
    fn apply_update(mut self, dto: UpdateDataConsentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.data_category = dto.data_category;
        self.lawful_basis = dto.lawful_basis;
        self.consent_given_at = dto.consent_given_at;
        self.consent_method = dto.consent_method;
        self.privacy_notice_version = dto.privacy_notice_version;
        self.retention_until = dto.retention_until;
        self.withdrawn_at = dto.withdrawn_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DataConsent here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

