//! EmployeeBankAccount DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EmployeeBankAccount;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EmployeeBankAccount
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmployeeBankAccountDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_id")]
    pub bank_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "account_number")]
    pub account_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_name")]
    pub account_name: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EmployeeBankAccount
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmployeeBankAccountDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "bank_id")]
    pub bank_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "account_number")]
    pub account_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "account_name")]
    pub account_name: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EmployeeBankAccount
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmployeeBankAccountDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bank_id")]
    pub bank_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_number")]
    pub account_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_name")]
    pub account_name: Option<String>,
}

impl PatchEmployeeBankAccountDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.bank_id.is_some() || self.account_number.is_some() || self.account_name.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EmployeeBankAccount entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBankAccountResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub bank_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_number: String,
    pub account_name: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EmployeeBankAccount entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBankAccountListResponseDto {
    /// List of items
    pub items: Vec<EmployeeBankAccountResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmployeeBankAccountListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmployeeBankAccountResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBankAccountSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub bank_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EmployeeBankAccount> for EmployeeBankAccountResponseDto {
    fn from(entity: EmployeeBankAccount) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            bank_id: entity.bank_id,
            account_number: entity.account_number,
            account_name: entity.account_name,
            metadata: entity.metadata,
        }
    }
}

impl From<EmployeeBankAccount> for EmployeeBankAccountSummaryDto {
    fn from(entity: EmployeeBankAccount) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            bank_id: entity.bank_id,
            created_at,
        }
    }
}

impl From<CreateEmployeeBankAccountDto> for EmployeeBankAccount {
    fn from(dto: CreateEmployeeBankAccountDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            bank_id: dto.bank_id,
            account_number: dto.account_number,
            account_name: dto.account_name,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EmployeeBankAccount> for EmployeeBankAccountResponseDto {
    fn from(entity: &EmployeeBankAccount) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            bank_id: entity.bank_id.clone(),
            account_number: entity.account_number.clone(),
            account_name: entity.account_name.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmployeeBankAccountDto> for EmployeeBankAccount {
    fn from_create_dto(dto: CreateEmployeeBankAccountDto) -> backbone_core::ServiceResult<Self> {
        Ok(EmployeeBankAccount::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmployeeBankAccountDto> for EmployeeBankAccount {
    fn apply_update(mut self, dto: UpdateEmployeeBankAccountDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.bank_id = dto.bank_id;
        self.account_number = dto.account_number;
        self.account_name = dto.account_name;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EmployeeBankAccount here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

