//! Employment DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Employment;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EmploymentState;
use crate::domain::entity::EmploymentStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Employment
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmploymentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "employment_status")]
    pub employment_status: EmploymentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "join_date")]
    pub join_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_join_date")]
    pub end_join_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id")]
    pub level_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "direct_manager_id")]
    pub direct_manager_id: Option<Uuid>,
    pub status: EmploymentState,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Employment
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmploymentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "employment_status")]
    pub employment_status: EmploymentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "join_date")]
    pub join_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_join_date")]
    pub end_join_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id")]
    pub level_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "direct_manager_id")]
    pub direct_manager_id: Option<Uuid>,
    pub status: EmploymentState,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Employment
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmploymentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_status")]
    pub employment_status: Option<EmploymentStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "join_date")]
    pub join_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_join_date")]
    pub end_join_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "level_id")]
    pub level_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "direct_manager_id")]
    pub direct_manager_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EmploymentState>,
}

impl PatchEmploymentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.employment_status.is_some() || self.join_date.is_some() || self.end_join_date.is_some() || self.department_id.is_some() || self.level_id.is_some() || self.position_id.is_some() || self.direct_manager_id.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Employment entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub employment_status: EmploymentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub join_date: NaiveDate,
    pub end_join_date: Option<NaiveDate>,
    pub department_id: Option<Uuid>,
    pub level_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    pub direct_manager_id: Option<Uuid>,
    pub status: EmploymentState,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Employment entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentListResponseDto {
    /// List of items
    pub items: Vec<EmploymentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmploymentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmploymentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub employment_status: EmploymentStatus,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Employment> for EmploymentResponseDto {
    fn from(entity: Employment) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            employment_status: entity.employment_status,
            join_date: entity.join_date,
            end_join_date: entity.end_join_date,
            department_id: entity.department_id,
            level_id: entity.level_id,
            position_id: entity.position_id,
            direct_manager_id: entity.direct_manager_id,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Employment> for EmploymentSummaryDto {
    fn from(entity: Employment) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            employment_status: entity.employment_status,
            created_at,
        }
    }
}

impl From<CreateEmploymentDto> for Employment {
    fn from(dto: CreateEmploymentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            employment_status: dto.employment_status,
            join_date: dto.join_date,
            end_join_date: dto.end_join_date,
            department_id: dto.department_id,
            level_id: dto.level_id,
            position_id: dto.position_id,
            direct_manager_id: dto.direct_manager_id,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Employment> for EmploymentResponseDto {
    fn from(entity: &Employment) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            employment_status: entity.employment_status.clone(),
            join_date: entity.join_date.clone(),
            end_join_date: entity.end_join_date.clone(),
            department_id: entity.department_id.clone(),
            level_id: entity.level_id.clone(),
            position_id: entity.position_id.clone(),
            direct_manager_id: entity.direct_manager_id.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmploymentDto> for Employment {
    fn from_create_dto(dto: CreateEmploymentDto) -> backbone_core::ServiceResult<Self> {
        Ok(Employment::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmploymentDto> for Employment {
    fn apply_update(mut self, dto: UpdateEmploymentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.employment_status = dto.employment_status;
        self.join_date = dto.join_date;
        self.end_join_date = dto.end_join_date;
        self.department_id = dto.department_id;
        self.level_id = dto.level_id;
        self.position_id = dto.position_id;
        self.direct_manager_id = dto.direct_manager_id;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Employment here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

