//! EmploymentHistory DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EmploymentHistory;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EmploymentAction;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EmploymentHistory
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmploymentHistoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_date")]
    pub effective_date: NaiveDate,
    pub action: EmploymentAction,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EmploymentHistory
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmploymentHistoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_date")]
    pub effective_date: NaiveDate,
    pub action: EmploymentAction,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EmploymentHistory
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmploymentHistoryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_date")]
    pub effective_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<EmploymentAction>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl PatchEmploymentHistoryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.effective_date.is_some() || self.action.is_some() || self.position_id_from.is_some() || self.position_id_to.is_some() || self.level_id_from.is_some() || self.level_id_to.is_some() || self.department_id_from.is_some() || self.department_id_to.is_some() || self.reference_id.is_some() || self.note.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EmploymentHistory entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentHistoryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub effective_date: NaiveDate,
    pub action: EmploymentAction,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub reference_id: Option<Uuid>,
    pub note: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EmploymentHistory entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentHistoryListResponseDto {
    /// List of items
    pub items: Vec<EmploymentHistoryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmploymentHistoryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmploymentHistoryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmploymentHistorySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub effective_date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EmploymentHistory> for EmploymentHistoryResponseDto {
    fn from(entity: EmploymentHistory) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            effective_date: entity.effective_date,
            action: entity.action,
            position_id_from: entity.position_id_from,
            position_id_to: entity.position_id_to,
            level_id_from: entity.level_id_from,
            level_id_to: entity.level_id_to,
            department_id_from: entity.department_id_from,
            department_id_to: entity.department_id_to,
            reference_id: entity.reference_id,
            note: entity.note,
            metadata: entity.metadata,
        }
    }
}

impl From<EmploymentHistory> for EmploymentHistorySummaryDto {
    fn from(entity: EmploymentHistory) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            effective_date: entity.effective_date,
            created_at,
        }
    }
}

impl From<CreateEmploymentHistoryDto> for EmploymentHistory {
    fn from(dto: CreateEmploymentHistoryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            effective_date: dto.effective_date,
            action: dto.action,
            position_id_from: dto.position_id_from,
            position_id_to: dto.position_id_to,
            level_id_from: dto.level_id_from,
            level_id_to: dto.level_id_to,
            department_id_from: dto.department_id_from,
            department_id_to: dto.department_id_to,
            reference_id: dto.reference_id,
            note: dto.note,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EmploymentHistory> for EmploymentHistoryResponseDto {
    fn from(entity: &EmploymentHistory) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            effective_date: entity.effective_date.clone(),
            action: entity.action.clone(),
            position_id_from: entity.position_id_from.clone(),
            position_id_to: entity.position_id_to.clone(),
            level_id_from: entity.level_id_from.clone(),
            level_id_to: entity.level_id_to.clone(),
            department_id_from: entity.department_id_from.clone(),
            department_id_to: entity.department_id_to.clone(),
            reference_id: entity.reference_id.clone(),
            note: entity.note.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmploymentHistoryDto> for EmploymentHistory {
    fn from_create_dto(dto: CreateEmploymentHistoryDto) -> backbone_core::ServiceResult<Self> {
        Ok(EmploymentHistory::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmploymentHistoryDto> for EmploymentHistory {
    fn apply_update(mut self, dto: UpdateEmploymentHistoryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.effective_date = dto.effective_date;
        self.action = dto.action;
        self.position_id_from = dto.position_id_from;
        self.position_id_to = dto.position_id_to;
        self.level_id_from = dto.level_id_from;
        self.level_id_to = dto.level_id_to;
        self.department_id_from = dto.department_id_from;
        self.department_id_to = dto.department_id_to;
        self.reference_id = dto.reference_id;
        self.note = dto.note;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EmploymentHistory here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

