//! EmployeeBpjs DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EmployeeBpjs;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EmployeeBpjs
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmployeeBpjsDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_number")]
    pub bpjs_ketenagakerjaan_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "npp_bpjs_ketenagakerjaan")]
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_date")]
    pub bpjs_ketenagakerjaan_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_number")]
    pub bpjs_kesehatan_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_family")]
    pub bpjs_kesehatan_family: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_date")]
    pub bpjs_kesehatan_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "jaminan_pensiun_date")]
    pub jaminan_pensiun_date: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EmployeeBpjs
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmployeeBpjsDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_number")]
    pub bpjs_ketenagakerjaan_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "npp_bpjs_ketenagakerjaan")]
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_date")]
    pub bpjs_ketenagakerjaan_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_number")]
    pub bpjs_kesehatan_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_family")]
    pub bpjs_kesehatan_family: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_date")]
    pub bpjs_kesehatan_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "jaminan_pensiun_date")]
    pub jaminan_pensiun_date: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EmployeeBpjs
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmployeeBpjsDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_number")]
    pub bpjs_ketenagakerjaan_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "npp_bpjs_ketenagakerjaan")]
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bpjs_ketenagakerjaan_date")]
    pub bpjs_ketenagakerjaan_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_number")]
    pub bpjs_kesehatan_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_family")]
    pub bpjs_kesehatan_family: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "bpjs_kesehatan_date")]
    pub bpjs_kesehatan_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "jaminan_pensiun_date")]
    pub jaminan_pensiun_date: Option<NaiveDate>,
}

impl PatchEmployeeBpjsDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.bpjs_ketenagakerjaan_number.is_some() || self.npp_bpjs_ketenagakerjaan.is_some() || self.bpjs_ketenagakerjaan_date.is_some() || self.bpjs_kesehatan_number.is_some() || self.bpjs_kesehatan_family.is_some() || self.bpjs_kesehatan_date.is_some() || self.jaminan_pensiun_date.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EmployeeBpjs entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBpjsResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub bpjs_ketenagakerjaan_number: Option<String>,
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    pub bpjs_ketenagakerjaan_date: Option<NaiveDate>,
    pub bpjs_kesehatan_number: Option<String>,
    pub bpjs_kesehatan_family: Option<i32>,
    pub bpjs_kesehatan_date: Option<NaiveDate>,
    pub jaminan_pensiun_date: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EmployeeBpjs entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBpjsListResponseDto {
    /// List of items
    pub items: Vec<EmployeeBpjsResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmployeeBpjsListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmployeeBpjsResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeBpjsSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub bpjs_ketenagakerjaan_number: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EmployeeBpjs> for EmployeeBpjsResponseDto {
    fn from(entity: EmployeeBpjs) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            bpjs_ketenagakerjaan_number: entity.bpjs_ketenagakerjaan_number,
            npp_bpjs_ketenagakerjaan: entity.npp_bpjs_ketenagakerjaan,
            bpjs_ketenagakerjaan_date: entity.bpjs_ketenagakerjaan_date,
            bpjs_kesehatan_number: entity.bpjs_kesehatan_number,
            bpjs_kesehatan_family: entity.bpjs_kesehatan_family,
            bpjs_kesehatan_date: entity.bpjs_kesehatan_date,
            jaminan_pensiun_date: entity.jaminan_pensiun_date,
            metadata: entity.metadata,
        }
    }
}

impl From<EmployeeBpjs> for EmployeeBpjsSummaryDto {
    fn from(entity: EmployeeBpjs) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            bpjs_ketenagakerjaan_number: entity.bpjs_ketenagakerjaan_number,
            created_at,
        }
    }
}

impl From<CreateEmployeeBpjsDto> for EmployeeBpjs {
    fn from(dto: CreateEmployeeBpjsDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            bpjs_ketenagakerjaan_number: dto.bpjs_ketenagakerjaan_number,
            npp_bpjs_ketenagakerjaan: dto.npp_bpjs_ketenagakerjaan,
            bpjs_ketenagakerjaan_date: dto.bpjs_ketenagakerjaan_date,
            bpjs_kesehatan_number: dto.bpjs_kesehatan_number,
            bpjs_kesehatan_family: dto.bpjs_kesehatan_family,
            bpjs_kesehatan_date: dto.bpjs_kesehatan_date,
            jaminan_pensiun_date: dto.jaminan_pensiun_date,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EmployeeBpjs> for EmployeeBpjsResponseDto {
    fn from(entity: &EmployeeBpjs) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            bpjs_ketenagakerjaan_number: entity.bpjs_ketenagakerjaan_number.clone(),
            npp_bpjs_ketenagakerjaan: entity.npp_bpjs_ketenagakerjaan.clone(),
            bpjs_ketenagakerjaan_date: entity.bpjs_ketenagakerjaan_date.clone(),
            bpjs_kesehatan_number: entity.bpjs_kesehatan_number.clone(),
            bpjs_kesehatan_family: entity.bpjs_kesehatan_family.clone(),
            bpjs_kesehatan_date: entity.bpjs_kesehatan_date.clone(),
            jaminan_pensiun_date: entity.jaminan_pensiun_date.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmployeeBpjsDto> for EmployeeBpjs {
    fn from_create_dto(dto: CreateEmployeeBpjsDto) -> backbone_core::ServiceResult<Self> {
        Ok(EmployeeBpjs::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmployeeBpjsDto> for EmployeeBpjs {
    fn apply_update(mut self, dto: UpdateEmployeeBpjsDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.bpjs_ketenagakerjaan_number = dto.bpjs_ketenagakerjaan_number;
        self.npp_bpjs_ketenagakerjaan = dto.npp_bpjs_ketenagakerjaan;
        self.bpjs_ketenagakerjaan_date = dto.bpjs_ketenagakerjaan_date;
        self.bpjs_kesehatan_number = dto.bpjs_kesehatan_number;
        self.bpjs_kesehatan_family = dto.bpjs_kesehatan_family;
        self.bpjs_kesehatan_date = dto.bpjs_kesehatan_date;
        self.jaminan_pensiun_date = dto.jaminan_pensiun_date;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EmployeeBpjs here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

