//! EmployeeTax DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EmployeeTax;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PtkpTier;
use crate::domain::entity::TaxMethod;
use crate::domain::entity::TaxSalary;
use crate::domain::entity::TerCategory;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EmployeeTax
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmployeeTaxDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "npwp_number")]
    pub npwp_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ptkp_override")]
    pub ptkp_override: Option<PtkpTier>,
    #[serde(alias = "tax_method")]
    pub tax_method: TaxMethod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ter_category")]
    pub ter_category: Option<TerCategory>,
    #[serde(alias = "tax_salary")]
    pub tax_salary: TaxSalary,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "taxable_date")]
    pub taxable_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "beginning_netto")]
    pub beginning_netto: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pph21_paid")]
    pub pph21_paid: Option<Decimal>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EmployeeTax
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmployeeTaxDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "npwp_number")]
    pub npwp_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ptkp_override")]
    pub ptkp_override: Option<PtkpTier>,
    #[serde(alias = "tax_method")]
    pub tax_method: TaxMethod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ter_category")]
    pub ter_category: Option<TerCategory>,
    #[serde(alias = "tax_salary")]
    pub tax_salary: TaxSalary,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "taxable_date")]
    pub taxable_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "beginning_netto")]
    pub beginning_netto: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pph21_paid")]
    pub pph21_paid: Option<Decimal>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EmployeeTax
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmployeeTaxDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "npwp_number")]
    pub npwp_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "ptkp_override")]
    pub ptkp_override: Option<PtkpTier>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_method")]
    pub tax_method: Option<TaxMethod>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "ter_category")]
    pub ter_category: Option<TerCategory>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_salary")]
    pub tax_salary: Option<TaxSalary>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "taxable_date")]
    pub taxable_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "beginning_netto")]
    pub beginning_netto: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "pph21_paid")]
    pub pph21_paid: Option<Decimal>,
}

impl PatchEmployeeTaxDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.npwp_number.is_some() || self.ptkp_override.is_some() || self.tax_method.is_some() || self.ter_category.is_some() || self.tax_salary.is_some() || self.taxable_date.is_some() || self.beginning_netto.is_some() || self.pph21_paid.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EmployeeTax entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeTaxResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub npwp_number: Option<String>,
    pub ptkp_override: Option<PtkpTier>,
    pub tax_method: TaxMethod,
    pub ter_category: Option<TerCategory>,
    pub tax_salary: TaxSalary,
    pub taxable_date: Option<NaiveDate>,
    pub beginning_netto: Option<Decimal>,
    pub pph21_paid: Option<Decimal>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EmployeeTax entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeTaxListResponseDto {
    /// List of items
    pub items: Vec<EmployeeTaxResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmployeeTaxListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmployeeTaxResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeTaxSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub npwp_number: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EmployeeTax> for EmployeeTaxResponseDto {
    fn from(entity: EmployeeTax) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            npwp_number: entity.npwp_number,
            ptkp_override: entity.ptkp_override,
            tax_method: entity.tax_method,
            ter_category: entity.ter_category,
            tax_salary: entity.tax_salary,
            taxable_date: entity.taxable_date,
            beginning_netto: entity.beginning_netto,
            pph21_paid: entity.pph21_paid,
            metadata: entity.metadata,
        }
    }
}

impl From<EmployeeTax> for EmployeeTaxSummaryDto {
    fn from(entity: EmployeeTax) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            npwp_number: entity.npwp_number,
            created_at,
        }
    }
}

impl From<CreateEmployeeTaxDto> for EmployeeTax {
    fn from(dto: CreateEmployeeTaxDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            npwp_number: dto.npwp_number,
            ptkp_override: dto.ptkp_override,
            tax_method: dto.tax_method,
            ter_category: dto.ter_category,
            tax_salary: dto.tax_salary,
            taxable_date: dto.taxable_date,
            beginning_netto: dto.beginning_netto,
            pph21_paid: dto.pph21_paid,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EmployeeTax> for EmployeeTaxResponseDto {
    fn from(entity: &EmployeeTax) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            npwp_number: entity.npwp_number.clone(),
            ptkp_override: entity.ptkp_override.clone(),
            tax_method: entity.tax_method.clone(),
            ter_category: entity.ter_category.clone(),
            tax_salary: entity.tax_salary.clone(),
            taxable_date: entity.taxable_date.clone(),
            beginning_netto: entity.beginning_netto.clone(),
            pph21_paid: entity.pph21_paid.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmployeeTaxDto> for EmployeeTax {
    fn from_create_dto(dto: CreateEmployeeTaxDto) -> backbone_core::ServiceResult<Self> {
        Ok(EmployeeTax::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmployeeTaxDto> for EmployeeTax {
    fn apply_update(mut self, dto: UpdateEmployeeTaxDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.npwp_number = dto.npwp_number;
        self.ptkp_override = dto.ptkp_override;
        self.tax_method = dto.tax_method;
        self.ter_category = dto.ter_category;
        self.tax_salary = dto.tax_salary;
        self.taxable_date = dto.taxable_date;
        self.beginning_netto = dto.beginning_netto;
        self.pph21_paid = dto.pph21_paid;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EmployeeTax here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

