//! RecordChangeRequest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::RecordChangeRequest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::RecordChangeStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new RecordChangeRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRecordChangeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "field_path")]
    pub field_path: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_value")]
    pub current_value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_value")]
    pub proposed_value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub status: RecordChangeStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_at")]
    pub applied_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a RecordChangeRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRecordChangeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "field_path")]
    pub field_path: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_value")]
    pub current_value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_value")]
    pub proposed_value: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub status: RecordChangeStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_at")]
    pub applied_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a RecordChangeRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRecordChangeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "field_path")]
    pub field_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "current_value")]
    pub current_value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "proposed_value")]
    pub proposed_value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<RecordChangeStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "applied_at")]
    pub applied_at: Option<DateTime<Utc>>,
}

impl PatchRecordChangeRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.field_path.is_some() || self.current_value.is_some() || self.proposed_value.is_some() || self.reason.is_some() || self.status.is_some() || self.approval_request_id.is_some() || self.decided_at.is_some() || self.applied_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for RecordChangeRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecordChangeRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub field_path: String,
    pub current_value: Option<String>,
    pub proposed_value: Option<String>,
    pub reason: Option<String>,
    pub status: RecordChangeStatus,
    pub approval_request_id: Option<Uuid>,
    pub decided_at: Option<DateTime<Utc>>,
    pub applied_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for RecordChangeRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecordChangeRequestListResponseDto {
    /// List of items
    pub items: Vec<RecordChangeRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RecordChangeRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RecordChangeRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RecordChangeRequestSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub field_path: String,
    pub current_value: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<RecordChangeRequest> for RecordChangeRequestResponseDto {
    fn from(entity: RecordChangeRequest) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            field_path: entity.field_path,
            current_value: entity.current_value,
            proposed_value: entity.proposed_value,
            reason: entity.reason,
            status: entity.status,
            approval_request_id: entity.approval_request_id,
            decided_at: entity.decided_at,
            applied_at: entity.applied_at,
            metadata: entity.metadata,
        }
    }
}

impl From<RecordChangeRequest> for RecordChangeRequestSummaryDto {
    fn from(entity: RecordChangeRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            field_path: entity.field_path,
            current_value: entity.current_value,
            created_at,
        }
    }
}

impl From<CreateRecordChangeRequestDto> for RecordChangeRequest {
    fn from(dto: CreateRecordChangeRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            field_path: dto.field_path,
            current_value: dto.current_value,
            proposed_value: dto.proposed_value,
            reason: dto.reason,
            status: dto.status,
            approval_request_id: dto.approval_request_id,
            decided_at: dto.decided_at,
            applied_at: dto.applied_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&RecordChangeRequest> for RecordChangeRequestResponseDto {
    fn from(entity: &RecordChangeRequest) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            field_path: entity.field_path.clone(),
            current_value: entity.current_value.clone(),
            proposed_value: entity.proposed_value.clone(),
            reason: entity.reason.clone(),
            status: entity.status.clone(),
            approval_request_id: entity.approval_request_id.clone(),
            decided_at: entity.decided_at.clone(),
            applied_at: entity.applied_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRecordChangeRequestDto> for RecordChangeRequest {
    fn from_create_dto(dto: CreateRecordChangeRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(RecordChangeRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRecordChangeRequestDto> for RecordChangeRequest {
    fn apply_update(mut self, dto: UpdateRecordChangeRequestDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.field_path = dto.field_path;
        self.current_value = dto.current_value;
        self.proposed_value = dto.proposed_value;
        self.reason = dto.reason;
        self.status = dto.status;
        self.approval_request_id = dto.approval_request_id;
        self.decided_at = dto.decided_at;
        self.applied_at = dto.applied_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to RecordChangeRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
