//! Domain policy for EmployeeBankAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::EmployeeBankAccount;

/// Domain policy for EmployeeBankAccount — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<EmployeeBankAccount>` in the `// <<< CUSTOM` zone.
pub type EmployeeBankAccountDomainPolicy = PermitAllPolicy<EmployeeBankAccount>;

// <<< CUSTOM
// END CUSTOM
