//! Domain policy for Example aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Example;

/// Domain policy for Example — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Example>` in the `// <<< CUSTOM` zone.
pub type ExampleDomainPolicy = PermitAllPolicy<Example>;

// <<< CUSTOM
// END CUSTOM
