//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod bank_domain_policy;
pub mod data_consent_domain_policy;
pub mod data_subject_request_domain_policy;
pub mod employee_domain_policy;
pub mod employee_bank_account_domain_policy;
pub mod employee_bpjs_domain_policy;
pub mod employee_certification_domain_policy;
pub mod employee_contact_domain_policy;
pub mod employee_education_domain_policy;
pub mod employee_family_domain_policy;
pub mod employee_identity_domain_policy;
pub mod employee_tax_domain_policy;
pub mod employee_work_experience_domain_policy;
pub mod employment_domain_policy;
pub mod employment_history_domain_policy;
pub mod pii_access_log_domain_policy;
pub mod religion_domain_policy;

pub use bank_domain_policy::BankDomainPolicy;
pub use data_consent_domain_policy::DataConsentDomainPolicy;
pub use data_subject_request_domain_policy::DataSubjectRequestDomainPolicy;
pub use employee_domain_policy::EmployeeDomainPolicy;
pub use employee_bank_account_domain_policy::EmployeeBankAccountDomainPolicy;
pub use employee_bpjs_domain_policy::EmployeeBpjsDomainPolicy;
pub use employee_certification_domain_policy::EmployeeCertificationDomainPolicy;
pub use employee_contact_domain_policy::EmployeeContactDomainPolicy;
pub use employee_education_domain_policy::EmployeeEducationDomainPolicy;
pub use employee_family_domain_policy::EmployeeFamilyDomainPolicy;
pub use employee_identity_domain_policy::EmployeeIdentityDomainPolicy;
pub use employee_tax_domain_policy::EmployeeTaxDomainPolicy;
pub use employee_work_experience_domain_policy::EmployeeWorkExperienceDomainPolicy;
pub use employment_domain_policy::EmploymentDomainPolicy;
pub use employment_history_domain_policy::EmploymentHistoryDomainPolicy;
pub use pii_access_log_domain_policy::PiiAccessLogDomainPolicy;
pub use religion_domain_policy::ReligionDomainPolicy;

// <<< CUSTOM
// END CUSTOM
