//! Application service for DataSubjectRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `data_subject_request_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDataSubjectRequestDto, UpdateDataSubjectRequestDto};
use crate::domain::entity::DataSubjectRequest;
use crate::infrastructure::persistence::DataSubjectRequestRepository;

/// Application service for DataSubjectRequest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `data_subject_request_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DataSubjectRequestServiceCustom {
///     inner: Arc<DataSubjectRequestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DataSubjectRequestService = GenericCrudService<
    DataSubjectRequest,
    CreateDataSubjectRequestDto,
    UpdateDataSubjectRequestDto,
    DataSubjectRequestRepository,
>;

// <<< CUSTOM
// END CUSTOM
