//! Application service for DataConsent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `data_consent_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDataConsentDto, UpdateDataConsentDto};
use crate::domain::entity::DataConsent;
use crate::infrastructure::persistence::DataConsentRepository;

/// Application service for DataConsent entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `data_consent_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DataConsentServiceCustom {
///     inner: Arc<DataConsentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DataConsentService = GenericCrudService<
    DataConsent,
    CreateDataConsentDto,
    UpdateDataConsentDto,
    DataConsentRepository,
>;

// <<< CUSTOM
// END CUSTOM
