//! Application service for EmployeeTax entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `employee_tax_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEmployeeTaxDto, UpdateEmployeeTaxDto};
use crate::domain::entity::EmployeeTax;
use crate::infrastructure::persistence::EmployeeTaxRepository;

/// Application service for EmployeeTax entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `employee_tax_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EmployeeTaxServiceCustom {
///     inner: Arc<EmployeeTaxService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EmployeeTaxService = GenericCrudService<
    EmployeeTax,
    CreateEmployeeTaxDto,
    UpdateEmployeeTaxDto,
    EmployeeTaxRepository,
>;

// <<< CUSTOM
// END CUSTOM
