//! Application service for EmployeeBankAccount entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `employee_bank_account_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEmployeeBankAccountDto, UpdateEmployeeBankAccountDto};
use crate::domain::entity::EmployeeBankAccount;
use crate::infrastructure::persistence::EmployeeBankAccountRepository;

/// Application service for EmployeeBankAccount entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `employee_bank_account_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EmployeeBankAccountServiceCustom {
///     inner: Arc<EmployeeBankAccountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EmployeeBankAccountService = GenericCrudService<
    EmployeeBankAccount,
    CreateEmployeeBankAccountDto,
    UpdateEmployeeBankAccountDto,
    EmployeeBankAccountRepository,
>;

// <<< CUSTOM
// END CUSTOM
