-- DataSubjectRequest Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the employee.data_subject_requests table.
-- Customize this file to add your initial data.

-- INSERT INTO employee.data_subject_requests (
--     id,
--     company_id,
--     employee_id,
--     request_type,
--     status,
--     requested_at,
--     fulfilled_at,
--     response,
--     note,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO employee.data_subject_requests (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

