-- EmployeeBpjs Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the employee.employee_bpjs table.
-- Customize this file to add your initial data.

-- INSERT INTO employee.employee_bpjs (
--     id,
--     company_id,
--     employee_id,
--     bpjs_ketenagakerjaan_number,
--     npp_bpjs_ketenagakerjaan,
--     bpjs_ketenagakerjaan_date,
--     bpjs_kesehatan_number,
--     bpjs_kesehatan_family,
--     bpjs_kesehatan_date,
--     jaminan_pensiun_date,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO employee.employee_bpjs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

