-- Employee Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the employee.employees table.
-- Customize this file to add your initial data.

-- INSERT INTO employee.employees (
--     id,
--     company_id,
--     employee_number,
--     user_id,
--     first_name,
--     last_name,
--     email,
--     mobile_phone,
--     phone,
--     birth_place,
--     birth_date,
--     gender,
--     marital_status,
--     blood_type,
--     religion_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO employee.employees (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

