-- PiiAccessLog Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the employee.pii_access_logs table.
-- Customize this file to add your initial data.

-- INSERT INTO employee.pii_access_logs (
--     id,
--     company_id,
--     employee_id,
--     accessed_by,
--     data_category,
--     purpose,
--     accessed_at
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO employee.pii_access_logs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

