-- RecordChangeRequest Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the employee.record_change_requests table.
-- Customize this file to add your initial data.

-- INSERT INTO employee.record_change_requests (
--     id,
--     employee_id,
--     field_path,
--     current_value,
--     proposed_value,
--     reason,
--     status,
--     approval_request_id,
--     decided_at,
--     applied_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO employee.record_change_requests (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

