-- Migration: Create employments table
-- Generated by metaphor-schema

-- Create employment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_status') THEN
        CREATE TYPE employment_status AS ENUM ('permanent', 'contract', 'probation', 'associate');
    END IF;
END
$$;

-- Create employment_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_state') THEN
        CREATE TYPE employment_state AS ENUM ('active', 'inactive');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.employments (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    employment_status employment_status NOT NULL DEFAULT 'permanent',
    join_date DATE NOT NULL,
    end_join_date DATE,
    department_id UUID,
    level_id UUID,
    position_id UUID,
    direct_manager_id UUID,
    status employment_state NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employments_company_id_status ON employee.employments (company_id, status);

CREATE INDEX IF NOT EXISTS idx_employments_employee_id ON employee.employments (employee_id);

CREATE INDEX IF NOT EXISTS idx_employments_department_id ON employee.employments (department_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employments_metadata_gin ON employee.employments USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employments_metadata_deleted_at ON employee.employments ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employments_metadata_created_at ON employee.employments ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employments_metadata_updated_at ON employee.employments ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.employments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employments_insert_audit ON employee.employments;
CREATE TRIGGER employments_insert_audit BEFORE INSERT ON employee.employments
    FOR EACH ROW EXECUTE FUNCTION employee.employments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employments_update_audit ON employee.employments;
CREATE TRIGGER employments_update_audit BEFORE UPDATE ON employee.employments
    FOR EACH ROW EXECUTE FUNCTION employee.employments_audit_timestamp();
