-- Migration: Create employee_families table
-- Generated by metaphor-schema

-- Create family_relationship enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'family_relationship') THEN
        CREATE TYPE family_relationship AS ENUM ('spouse', 'child', 'parent', 'sibling', 'other');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.employee_families (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    name TEXT NOT NULL,
    relationship family_relationship NOT NULL,
    birth_date DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employee_families_employee_id ON employee.employee_families (employee_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employee_families_metadata_gin ON employee.employee_families USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employee_families_metadata_deleted_at ON employee.employee_families ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employee_families_metadata_created_at ON employee.employee_families ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employee_families_metadata_updated_at ON employee.employee_families ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.employee_families_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_families_insert_audit ON employee.employee_families;
CREATE TRIGGER employee_families_insert_audit BEFORE INSERT ON employee.employee_families
    FOR EACH ROW EXECUTE FUNCTION employee.employee_families_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_families_update_audit ON employee.employee_families;
CREATE TRIGGER employee_families_update_audit BEFORE UPDATE ON employee.employee_families
    FOR EACH ROW EXECUTE FUNCTION employee.employee_families_audit_timestamp();
