-- Migration: Create employee_certifications table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.employee_certifications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    name TEXT NOT NULL,
    issuing_organization TEXT,
    start_date DATE,
    end_date DATE,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employee_certifications_employee_id ON employee.employee_certifications (employee_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employee_certifications_metadata_gin ON employee.employee_certifications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employee_certifications_metadata_deleted_at ON employee.employee_certifications ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employee_certifications_metadata_created_at ON employee.employee_certifications ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employee_certifications_metadata_updated_at ON employee.employee_certifications ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.employee_certifications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_certifications_insert_audit ON employee.employee_certifications;
CREATE TRIGGER employee_certifications_insert_audit BEFORE INSERT ON employee.employee_certifications
    FOR EACH ROW EXECUTE FUNCTION employee.employee_certifications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_certifications_update_audit ON employee.employee_certifications;
CREATE TRIGGER employee_certifications_update_audit BEFORE UPDATE ON employee.employee_certifications
    FOR EACH ROW EXECUTE FUNCTION employee.employee_certifications_audit_timestamp();
