-- Migration: Create data_consents table
-- Generated by metaphor-schema

-- Create data_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_category') THEN
        CREATE TYPE data_category AS ENUM ('identity', 'financial', 'family', 'contact', 'employment', 'health', 'biometric');
    END IF;
END
$$;

-- Create lawful_basis enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lawful_basis') THEN
        CREATE TYPE lawful_basis AS ENUM ('consent', 'contract', 'legal_obligation', 'employment', 'vital_interest', 'legitimate_interest');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.data_consents (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    data_category data_category NOT NULL,
    lawful_basis lawful_basis NOT NULL,
    consent_given_at TIMESTAMPTZ,
    consent_method TEXT,
    privacy_notice_version TEXT,
    retention_until DATE,
    withdrawn_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_data_consents_employee_id_data_category ON employee.data_consents (employee_id, data_category);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_data_consents_metadata_gin ON employee.data_consents USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_data_consents_metadata_deleted_at ON employee.data_consents ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_data_consents_metadata_created_at ON employee.data_consents ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_data_consents_metadata_updated_at ON employee.data_consents ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.data_consents_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS data_consents_insert_audit ON employee.data_consents;
CREATE TRIGGER data_consents_insert_audit BEFORE INSERT ON employee.data_consents
    FOR EACH ROW EXECUTE FUNCTION employee.data_consents_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS data_consents_update_audit ON employee.data_consents;
CREATE TRIGGER data_consents_update_audit BEFORE UPDATE ON employee.data_consents
    FOR EACH ROW EXECUTE FUNCTION employee.data_consents_audit_timestamp();
