-- Migration: Create pii_access_logs table
-- Generated by metaphor-schema

-- Create data_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_category') THEN
        CREATE TYPE data_category AS ENUM ('identity', 'financial', 'family', 'contact', 'employment', 'health', 'biometric');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.pii_access_logs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    accessed_by UUID NOT NULL,
    data_category data_category NOT NULL,
    purpose TEXT,
    accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pii_access_logs_employee_id_accessed_at ON employee.pii_access_logs (employee_id, accessed_at);

CREATE INDEX IF NOT EXISTS idx_pii_access_logs_accessed_by ON employee.pii_access_logs (accessed_by);
