-- Migration: Create data_subject_requests table
-- Generated by metaphor-schema

-- Create data_subject_right enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_subject_right') THEN
        CREATE TYPE data_subject_right AS ENUM ('access', 'rectify', 'erase', 'export', 'object', 'restrict');
    END IF;
END
$$;

-- Create dsar_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dsar_status') THEN
        CREATE TYPE dsar_status AS ENUM ('pending', 'in_progress', 'fulfilled', 'rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.data_subject_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    request_type data_subject_right NOT NULL,
    status dsar_status NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fulfilled_at TIMESTAMPTZ,
    response JSONB,
    note TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_data_subject_requests_company_id_status ON employee.data_subject_requests (company_id, status);

CREATE INDEX IF NOT EXISTS idx_data_subject_requests_employee_id ON employee.data_subject_requests (employee_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_data_subject_requests_metadata_gin ON employee.data_subject_requests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_data_subject_requests_metadata_deleted_at ON employee.data_subject_requests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_data_subject_requests_metadata_created_at ON employee.data_subject_requests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_data_subject_requests_metadata_updated_at ON employee.data_subject_requests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.data_subject_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS data_subject_requests_insert_audit ON employee.data_subject_requests;
CREATE TRIGGER data_subject_requests_insert_audit BEFORE INSERT ON employee.data_subject_requests
    FOR EACH ROW EXECUTE FUNCTION employee.data_subject_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS data_subject_requests_update_audit ON employee.data_subject_requests;
CREATE TRIGGER data_subject_requests_update_audit BEFORE UPDATE ON employee.data_subject_requests
    FOR EACH ROW EXECUTE FUNCTION employee.data_subject_requests_audit_timestamp();
