-- Migration: Create employment_histories table
-- Generated by metaphor-schema

-- Create employment_action enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_action') THEN
        CREATE TYPE employment_action AS ENUM ('hire', 'transfer', 'promotion', 'demotion', 'role_change', 'reinstatement');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.employment_histories (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    effective_date DATE NOT NULL,
    action employment_action NOT NULL,
    position_id_from UUID,
    position_id_to UUID,
    level_id_from UUID,
    level_id_to UUID,
    department_id_from UUID,
    department_id_to UUID,
    reference_id UUID,
    note TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employment_histories_employee_id_effective_date ON employee.employment_histories (employee_id, effective_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employment_histories_metadata_gin ON employee.employment_histories USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employment_histories_metadata_deleted_at ON employee.employment_histories ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employment_histories_metadata_created_at ON employee.employment_histories ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employment_histories_metadata_updated_at ON employee.employment_histories ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.employment_histories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employment_histories_insert_audit ON employee.employment_histories;
CREATE TRIGGER employment_histories_insert_audit BEFORE INSERT ON employee.employment_histories
    FOR EACH ROW EXECUTE FUNCTION employee.employment_histories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employment_histories_update_audit ON employee.employment_histories;
CREATE TRIGGER employment_histories_update_audit BEFORE UPDATE ON employee.employment_histories
    FOR EACH ROW EXECUTE FUNCTION employee.employment_histories_audit_timestamp();
