-- Migration: Create employee_identities table
-- Generated by metaphor-schema

-- Create identity_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'identity_type') THEN
        CREATE TYPE identity_type AS ENUM ('id', 'passport');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.employee_identities (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    identity_type identity_type NOT NULL,
    identity_number TEXT NOT NULL,
    identity_expiry_date DATE,
    is_permanent BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employee_identities_employee_id ON employee.employee_identities (employee_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employee_identities_metadata_gin ON employee.employee_identities USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employee_identities_metadata_deleted_at ON employee.employee_identities ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employee_identities_metadata_created_at ON employee.employee_identities ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employee_identities_metadata_updated_at ON employee.employee_identities ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.employee_identities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_identities_insert_audit ON employee.employee_identities;
CREATE TRIGGER employee_identities_insert_audit BEFORE INSERT ON employee.employee_identities
    FOR EACH ROW EXECUTE FUNCTION employee.employee_identities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_identities_update_audit ON employee.employee_identities;
CREATE TRIGGER employee_identities_update_audit BEFORE UPDATE ON employee.employee_identities
    FOR EACH ROW EXECUTE FUNCTION employee.employee_identities_audit_timestamp();
