-- Company fence posture for employee module (ADR-0014: strict)
-- Generated by metaphor-schema. Every company-scoped entity here carries company_id
-- and is fenced strict: a session sees only rows whose company_id equals the
-- request-scoped company (`set_config('app.company_id', <uuid>, true)`); an unset
-- var sees zero rows (fail-closed). These tables shipped company_id without a policy
-- since the pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). `banks` and `religions` are global reference
-- masters with no company_id — intentionally unfenced under any declaration.
-- Requires the app to connect as a non-superuser role; migrations/seeders run as
-- the owner and bypass.

-- Migration: company row-level-security fence for employee.data_consents
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.data_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.data_consents FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS data_consents_company_isolation ON employee.data_consents;
CREATE POLICY data_consents_company_isolation ON employee.data_consents
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.data_subject_requests
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.data_subject_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.data_subject_requests FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS data_subject_requests_company_isolation ON employee.data_subject_requests;
CREATE POLICY data_subject_requests_company_isolation ON employee.data_subject_requests
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_bank_accounts
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_bank_accounts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_bank_accounts_company_isolation ON employee.employee_bank_accounts;
CREATE POLICY employee_bank_accounts_company_isolation ON employee.employee_bank_accounts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_bpjs
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_bpjs ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_bpjs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_bpjs_company_isolation ON employee.employee_bpjs;
CREATE POLICY employee_bpjs_company_isolation ON employee.employee_bpjs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_certifications
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_certifications FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_certifications_company_isolation ON employee.employee_certifications;
CREATE POLICY employee_certifications_company_isolation ON employee.employee_certifications
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_contacts
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_contacts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_contacts_company_isolation ON employee.employee_contacts;
CREATE POLICY employee_contacts_company_isolation ON employee.employee_contacts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_educations
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_educations ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_educations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_educations_company_isolation ON employee.employee_educations;
CREATE POLICY employee_educations_company_isolation ON employee.employee_educations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_families
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_families ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_families FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_families_company_isolation ON employee.employee_families;
CREATE POLICY employee_families_company_isolation ON employee.employee_families
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_identities
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_identities FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_identities_company_isolation ON employee.employee_identities;
CREATE POLICY employee_identities_company_isolation ON employee.employee_identities
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_taxes
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_taxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_taxes FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_taxes_company_isolation ON employee.employee_taxes;
CREATE POLICY employee_taxes_company_isolation ON employee.employee_taxes
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employee_work_experiences
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employee_work_experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employee_work_experiences FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_work_experiences_company_isolation ON employee.employee_work_experiences;
CREATE POLICY employee_work_experiences_company_isolation ON employee.employee_work_experiences
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employees
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employees FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employees_company_isolation ON employee.employees;
CREATE POLICY employees_company_isolation ON employee.employees
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employment_histories
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employment_histories ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employment_histories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employment_histories_company_isolation ON employee.employment_histories;
CREATE POLICY employment_histories_company_isolation ON employee.employment_histories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.employments
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.employments ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.employments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employments_company_isolation ON employee.employments;
CREATE POLICY employments_company_isolation ON employee.employments
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for employee.pii_access_logs
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE employee.pii_access_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee.pii_access_logs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pii_access_logs_company_isolation ON employee.pii_access_logs;
CREATE POLICY pii_access_logs_company_isolation ON employee.pii_access_logs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
