-- Migration: Create banks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS employee;

CREATE TABLE IF NOT EXISTS employee.banks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_banks_name ON employee.banks (name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_banks_metadata_gin ON employee.banks USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_banks_metadata_deleted_at ON employee.banks ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_banks_metadata_created_at ON employee.banks ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_banks_metadata_updated_at ON employee.banks ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION employee.banks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS banks_insert_audit ON employee.banks;
CREATE TRIGGER banks_insert_audit BEFORE INSERT ON employee.banks
    FOR EACH ROW EXECUTE FUNCTION employee.banks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS banks_update_audit ON employee.banks;
CREATE TRIGGER banks_update_audit BEFORE UPDATE ON employee.banks
    FOR EACH ROW EXECUTE FUNCTION employee.banks_audit_timestamp();
