//! Event handler trait for DataSubjectRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DataSubjectRequestEvent;

/// Event handler for DataSubjectRequest events.
/// Implement this trait to react to DataSubjectRequest lifecycle events.
pub trait DataSubjectRequestEventHandler: EventHandler<DataSubjectRequestEvent> {}
