//! Event handler trait for Employment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmploymentEvent;

/// Event handler for Employment events.
/// Implement this trait to react to Employment lifecycle events.
pub trait EmploymentEventHandler: EventHandler<EmploymentEvent> {}
