//! Event handler trait for EmployeeTax events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeTaxEvent;

/// Event handler for EmployeeTax events.
/// Implement this trait to react to EmployeeTax lifecycle events.
pub trait EmployeeTaxEventHandler: EventHandler<EmployeeTaxEvent> {}
