//! Event handler trait for EmployeeWorkExperience events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeWorkExperienceEvent;

/// Event handler for EmployeeWorkExperience events.
/// Implement this trait to react to EmployeeWorkExperience lifecycle events.
pub trait EmployeeWorkExperienceEventHandler: EventHandler<EmployeeWorkExperienceEvent> {}
