//! Event handler trait for EmployeeEducation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeEducationEvent;

/// Event handler for EmployeeEducation events.
/// Implement this trait to react to EmployeeEducation lifecycle events.
pub trait EmployeeEducationEventHandler: EventHandler<EmployeeEducationEvent> {}
