//! Domain events for EmployeeWorkExperience entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmployeeWorkExperience;

/// Domain events for EmployeeWorkExperience — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmployeeWorkExperience>)` variant.
pub type EmployeeWorkExperienceEvent = CrudEvent<EmployeeWorkExperience>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmployeeWorkExperience events.
pub type EmployeeWorkExperienceEventPublisher = Arc<dyn CrudEventPublisher<EmployeeWorkExperience> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeWorkExperienceEventPublisher = NoOpCrudEventPublisher<EmployeeWorkExperience>;
