//! Domain events for EmployeeCertification entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmployeeCertification;

/// Domain events for EmployeeCertification — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmployeeCertification>)` variant.
pub type EmployeeCertificationEvent = CrudEvent<EmployeeCertification>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmployeeCertification events.
pub type EmployeeCertificationEventPublisher = Arc<dyn CrudEventPublisher<EmployeeCertification> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeCertificationEventPublisher = NoOpCrudEventPublisher<EmployeeCertification>;
