//! Domain events for EmployeeContact entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmployeeContact;

/// Domain events for EmployeeContact — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmployeeContact>)` variant.
pub type EmployeeContactEvent = CrudEvent<EmployeeContact>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmployeeContact events.
pub type EmployeeContactEventPublisher = Arc<dyn CrudEventPublisher<EmployeeContact> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeContactEventPublisher = NoOpCrudEventPublisher<EmployeeContact>;
