//! Event handler trait for EmploymentHistory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmploymentHistoryEvent;

/// Event handler for EmploymentHistory events.
/// Implement this trait to react to EmploymentHistory lifecycle events.
pub trait EmploymentHistoryEventHandler: EventHandler<EmploymentHistoryEvent> {}
