//! Domain events for EmploymentHistory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmploymentHistory;

/// Domain events for EmploymentHistory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmploymentHistory>)` variant.
pub type EmploymentHistoryEvent = CrudEvent<EmploymentHistory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmploymentHistory events.
pub type EmploymentHistoryEventPublisher = Arc<dyn CrudEventPublisher<EmploymentHistory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmploymentHistoryEventPublisher = NoOpCrudEventPublisher<EmploymentHistory>;
