//! Event handler trait for EmployeeBankAccount events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeBankAccountEvent;

/// Event handler for EmployeeBankAccount events.
/// Implement this trait to react to EmployeeBankAccount lifecycle events.
pub trait EmployeeBankAccountEventHandler: EventHandler<EmployeeBankAccountEvent> {}
