//! Domain events for RecordChangeRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RecordChangeRequest;

/// Domain events for RecordChangeRequest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RecordChangeRequest>)` variant.
pub type RecordChangeRequestEvent = CrudEvent<RecordChangeRequest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RecordChangeRequest events.
pub type RecordChangeRequestEventPublisher = Arc<dyn CrudEventPublisher<RecordChangeRequest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRecordChangeRequestEventPublisher = NoOpCrudEventPublisher<RecordChangeRequest>;
