//! Event handler trait for RecordChangeRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RecordChangeRequestEvent;

/// Event handler for RecordChangeRequest events.
/// Implement this trait to react to RecordChangeRequest lifecycle events.
pub trait RecordChangeRequestEventHandler: EventHandler<RecordChangeRequestEvent> {}
