//! Bank seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Bank data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// BANK SEEDER
// ============================================================================

/// Seeder for bank
pub struct SeedBankSeeder;

impl SeedBankSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedBankSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedBankSeeder {
    fn name(&self) -> &'static str {
        "SeedBankSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if employee.banks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM employee.banks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/bank_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM employee.banks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

