//! EmployeeWorkExperience seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EmployeeWorkExperience data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EMPLOYEEWORKEXPERIENCE SEEDER
// ============================================================================

/// Seeder for employee_work_experience
pub struct SeedEmployeeWorkExperienceSeeder;

impl SeedEmployeeWorkExperienceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEmployeeWorkExperienceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEmployeeWorkExperienceSeeder {
    fn name(&self) -> &'static str {
        "SeedEmployeeWorkExperienceSeeder"
    }

    fn order(&self) -> i32 {
        13
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if employee.employee_work_experiences table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM employee.employee_work_experiences")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/employee_work_experience_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM employee.employee_work_experiences")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

