//! EmployeeEducation seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial EmployeeEducation data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EMPLOYEEEDUCATION SEEDER
// ============================================================================

/// Seeder for employee_education
pub struct SeedEmployeeEducationSeeder;

impl SeedEmployeeEducationSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEmployeeEducationSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEmployeeEducationSeeder {
    fn name(&self) -> &'static str {
        "SeedEmployeeEducationSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if employee.employee_educations table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM employee.employee_educations")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/employee_education_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM employee.employee_educations")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

