//! Repository trait for DataSubjectRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DataSubjectRequest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DataSubjectRequest, DataSubjectRight, DsarStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DataSubjectRequestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DataSubjectRequestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DataSubjectRequestPaginatedResult {
    pub data: Vec<DataSubjectRequest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DataSubjectRequestFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub request_type: Option<DataSubjectRight>,
    pub status: Option<DsarStatus>,
    pub note: Option<String>,
}

impl DataSubjectRequestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.request_type.is_some() || self.status.is_some() || self.note.is_some()
    }
}

/// Repository trait for DataSubjectRequest aggregate
///
/// This trait defines the persistence contract for DataSubjectRequest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DataSubjectRequestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new data_subject_request entity
    async fn save(&self, entity: &DataSubjectRequest) -> Result<DataSubjectRequest>;

    /// Find data_subject_request by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DataSubjectRequest>>;

    /// Find all data_subject_request entities
    async fn find_all(&self) -> Result<Vec<DataSubjectRequest>>;

    /// Update data_subject_request by ID
    async fn update(&self, id: &str, entity: &DataSubjectRequest) -> Result<Option<DataSubjectRequest>>;

    /// Delete data_subject_request by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List data_subject_request with pagination
    async fn list(&self, params: DataSubjectRequestPaginationParams) -> Result<DataSubjectRequestPaginatedResult>;

    /// List data_subject_request with pagination and filters
    async fn list_with_filters(&self, params: DataSubjectRequestPaginationParams, filters: DataSubjectRequestFilter) -> Result<DataSubjectRequestPaginatedResult>;

    /// Count all data_subject_request entities
    async fn count(&self) -> Result<u64>;

    /// Count data_subject_request entities matching filters
    async fn count_with_filters(&self, filters: DataSubjectRequestFilter) -> Result<u64>;

    /// Check if data_subject_request exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete data_subject_request by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted data_subject_request by ID
    async fn restore(&self, id: &str) -> Result<Option<DataSubjectRequest>>;

    /// List soft-deleted data_subject_request entities
    async fn list_deleted(&self, params: DataSubjectRequestPaginationParams) -> Result<DataSubjectRequestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save data_subject_request entities
    async fn bulk_save(&self, entities: &[DataSubjectRequest]) -> Result<Vec<DataSubjectRequest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
