//! Repository trait for EmployeeBankAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeBankAccount aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmployeeBankAccount;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeBankAccountPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeBankAccountPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeBankAccountPaginatedResult {
    pub data: Vec<EmployeeBankAccount>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeBankAccountFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub bank_id: Option<Uuid>,
    pub account_number: Option<String>,
    pub account_name: Option<String>,
}

impl EmployeeBankAccountFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.bank_id.is_some() || self.account_number.is_some() || self.account_name.is_some()
    }
}

/// Repository trait for EmployeeBankAccount aggregate
///
/// This trait defines the persistence contract for EmployeeBankAccount entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeBankAccountRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_bank_account entity
    async fn save(&self, entity: &EmployeeBankAccount) -> Result<EmployeeBankAccount>;

    /// Find employee_bank_account by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeBankAccount>>;

    /// Find all employee_bank_account entities
    async fn find_all(&self) -> Result<Vec<EmployeeBankAccount>>;

    /// Update employee_bank_account by ID
    async fn update(&self, id: &str, entity: &EmployeeBankAccount) -> Result<Option<EmployeeBankAccount>>;

    /// Delete employee_bank_account by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_bank_account with pagination
    async fn list(&self, params: EmployeeBankAccountPaginationParams) -> Result<EmployeeBankAccountPaginatedResult>;

    /// List employee_bank_account with pagination and filters
    async fn list_with_filters(&self, params: EmployeeBankAccountPaginationParams, filters: EmployeeBankAccountFilter) -> Result<EmployeeBankAccountPaginatedResult>;

    /// Count all employee_bank_account entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_bank_account entities matching filters
    async fn count_with_filters(&self, filters: EmployeeBankAccountFilter) -> Result<u64>;

    /// Check if employee_bank_account exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_bank_account by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_bank_account by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeBankAccount>>;

    /// List soft-deleted employee_bank_account entities
    async fn list_deleted(&self, params: EmployeeBankAccountPaginationParams) -> Result<EmployeeBankAccountPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_bank_account entities
    async fn bulk_save(&self, entities: &[EmployeeBankAccount]) -> Result<Vec<EmployeeBankAccount>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
