//! Repository trait for EmployeeCertification aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeCertification aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmployeeCertification;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeCertificationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeCertificationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeCertificationPaginatedResult {
    pub data: Vec<EmployeeCertification>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeCertificationFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub name: Option<String>,
    pub issuing_organization: Option<String>,
    pub description: Option<String>,
}

impl EmployeeCertificationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.name.is_some() || self.issuing_organization.is_some() || self.description.is_some()
    }
}

/// Repository trait for EmployeeCertification aggregate
///
/// This trait defines the persistence contract for EmployeeCertification entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeCertificationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_certification entity
    async fn save(&self, entity: &EmployeeCertification) -> Result<EmployeeCertification>;

    /// Find employee_certification by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeCertification>>;

    /// Find all employee_certification entities
    async fn find_all(&self) -> Result<Vec<EmployeeCertification>>;

    /// Update employee_certification by ID
    async fn update(&self, id: &str, entity: &EmployeeCertification) -> Result<Option<EmployeeCertification>>;

    /// Delete employee_certification by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_certification with pagination
    async fn list(&self, params: EmployeeCertificationPaginationParams) -> Result<EmployeeCertificationPaginatedResult>;

    /// List employee_certification with pagination and filters
    async fn list_with_filters(&self, params: EmployeeCertificationPaginationParams, filters: EmployeeCertificationFilter) -> Result<EmployeeCertificationPaginatedResult>;

    /// Count all employee_certification entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_certification entities matching filters
    async fn count_with_filters(&self, filters: EmployeeCertificationFilter) -> Result<u64>;

    /// Check if employee_certification exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_certification by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_certification by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeCertification>>;

    /// List soft-deleted employee_certification entities
    async fn list_deleted(&self, params: EmployeeCertificationPaginationParams) -> Result<EmployeeCertificationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_certification entities
    async fn bulk_save(&self, entities: &[EmployeeCertification]) -> Result<Vec<EmployeeCertification>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
