//! Repository trait for EmploymentHistory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmploymentHistory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{EmploymentHistory, EmploymentAction};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmploymentHistoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmploymentHistoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmploymentHistoryPaginatedResult {
    pub data: Vec<EmploymentHistory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmploymentHistoryFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub action: Option<EmploymentAction>,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub reference_id: Option<Uuid>,
    pub note: Option<String>,
}

impl EmploymentHistoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.action.is_some() || self.position_id_from.is_some() || self.position_id_to.is_some() || self.level_id_from.is_some() || self.level_id_to.is_some() || self.department_id_from.is_some() || self.department_id_to.is_some() || self.reference_id.is_some() || self.note.is_some()
    }
}

/// Repository trait for EmploymentHistory aggregate
///
/// This trait defines the persistence contract for EmploymentHistory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmploymentHistoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employment_history entity
    async fn save(&self, entity: &EmploymentHistory) -> Result<EmploymentHistory>;

    /// Find employment_history by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmploymentHistory>>;

    /// Find all employment_history entities
    async fn find_all(&self) -> Result<Vec<EmploymentHistory>>;

    /// Update employment_history by ID
    async fn update(&self, id: &str, entity: &EmploymentHistory) -> Result<Option<EmploymentHistory>>;

    /// Delete employment_history by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employment_history with pagination
    async fn list(&self, params: EmploymentHistoryPaginationParams) -> Result<EmploymentHistoryPaginatedResult>;

    /// List employment_history with pagination and filters
    async fn list_with_filters(&self, params: EmploymentHistoryPaginationParams, filters: EmploymentHistoryFilter) -> Result<EmploymentHistoryPaginatedResult>;

    /// Count all employment_history entities
    async fn count(&self) -> Result<u64>;

    /// Count employment_history entities matching filters
    async fn count_with_filters(&self, filters: EmploymentHistoryFilter) -> Result<u64>;

    /// Check if employment_history exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employment_history by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employment_history by ID
    async fn restore(&self, id: &str) -> Result<Option<EmploymentHistory>>;

    /// List soft-deleted employment_history entities
    async fn list_deleted(&self, params: EmploymentHistoryPaginationParams) -> Result<EmploymentHistoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employment_history entities
    async fn bulk_save(&self, entities: &[EmploymentHistory]) -> Result<Vec<EmploymentHistory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
