//! Repository trait for EmployeeBpjs aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeBpjs aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmployeeBpjs;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeBpjsPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeBpjsPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeBpjsPaginatedResult {
    pub data: Vec<EmployeeBpjs>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeBpjsFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub bpjs_ketenagakerjaan_number: Option<String>,
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    pub bpjs_kesehatan_number: Option<String>,
}

impl EmployeeBpjsFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.bpjs_ketenagakerjaan_number.is_some() || self.npp_bpjs_ketenagakerjaan.is_some() || self.bpjs_kesehatan_number.is_some()
    }
}

/// Repository trait for EmployeeBpjs aggregate
///
/// This trait defines the persistence contract for EmployeeBpjs entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeBpjsRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_bpjs entity
    async fn save(&self, entity: &EmployeeBpjs) -> Result<EmployeeBpjs>;

    /// Find employee_bpjs by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeBpjs>>;

    /// Find all employee_bpjs entities
    async fn find_all(&self) -> Result<Vec<EmployeeBpjs>>;

    /// Update employee_bpjs by ID
    async fn update(&self, id: &str, entity: &EmployeeBpjs) -> Result<Option<EmployeeBpjs>>;

    /// Delete employee_bpjs by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_bpjs with pagination
    async fn list(&self, params: EmployeeBpjsPaginationParams) -> Result<EmployeeBpjsPaginatedResult>;

    /// List employee_bpjs with pagination and filters
    async fn list_with_filters(&self, params: EmployeeBpjsPaginationParams, filters: EmployeeBpjsFilter) -> Result<EmployeeBpjsPaginatedResult>;

    /// Count all employee_bpjs entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_bpjs entities matching filters
    async fn count_with_filters(&self, filters: EmployeeBpjsFilter) -> Result<u64>;

    /// Check if employee_bpjs exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_bpjs by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_bpjs by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeBpjs>>;

    /// List soft-deleted employee_bpjs entities
    async fn list_deleted(&self, params: EmployeeBpjsPaginationParams) -> Result<EmployeeBpjsPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_bpjs entities
    async fn bulk_save(&self, entities: &[EmployeeBpjs]) -> Result<Vec<EmployeeBpjs>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
