//! Repository trait for EmployeeWorkExperience aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeWorkExperience aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmployeeWorkExperience;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeWorkExperiencePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeWorkExperiencePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeWorkExperiencePaginatedResult {
    pub data: Vec<EmployeeWorkExperience>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeWorkExperienceFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub company_name: Option<String>,
    pub job_position: Option<String>,
}

impl EmployeeWorkExperienceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.company_name.is_some() || self.job_position.is_some()
    }
}

/// Repository trait for EmployeeWorkExperience aggregate
///
/// This trait defines the persistence contract for EmployeeWorkExperience entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeWorkExperienceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_work_experience entity
    async fn save(&self, entity: &EmployeeWorkExperience) -> Result<EmployeeWorkExperience>;

    /// Find employee_work_experience by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeWorkExperience>>;

    /// Find all employee_work_experience entities
    async fn find_all(&self) -> Result<Vec<EmployeeWorkExperience>>;

    /// Update employee_work_experience by ID
    async fn update(&self, id: &str, entity: &EmployeeWorkExperience) -> Result<Option<EmployeeWorkExperience>>;

    /// Delete employee_work_experience by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_work_experience with pagination
    async fn list(&self, params: EmployeeWorkExperiencePaginationParams) -> Result<EmployeeWorkExperiencePaginatedResult>;

    /// List employee_work_experience with pagination and filters
    async fn list_with_filters(&self, params: EmployeeWorkExperiencePaginationParams, filters: EmployeeWorkExperienceFilter) -> Result<EmployeeWorkExperiencePaginatedResult>;

    /// Count all employee_work_experience entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_work_experience entities matching filters
    async fn count_with_filters(&self, filters: EmployeeWorkExperienceFilter) -> Result<u64>;

    /// Check if employee_work_experience exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_work_experience by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_work_experience by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeWorkExperience>>;

    /// List soft-deleted employee_work_experience entities
    async fn list_deleted(&self, params: EmployeeWorkExperiencePaginationParams) -> Result<EmployeeWorkExperiencePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_work_experience entities
    async fn bulk_save(&self, entities: &[EmployeeWorkExperience]) -> Result<Vec<EmployeeWorkExperience>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
