//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod bank_repository;
pub mod data_consent_repository;
pub mod data_subject_request_repository;
pub mod employee_repository;
pub mod employee_bank_account_repository;
pub mod employee_bpjs_repository;
pub mod employee_certification_repository;
pub mod employee_contact_repository;
pub mod employee_education_repository;
pub mod employee_family_repository;
pub mod employee_identity_repository;
pub mod employee_tax_repository;
pub mod employee_work_experience_repository;
pub mod employment_repository;
pub mod employment_history_repository;
pub mod pii_access_log_repository;
pub mod religion_repository;

// Re-exports
pub use bank_repository::{
    BankRepository,
    BankPaginationParams,
    BankPaginatedResult,
    BankFilter,
};
pub use data_consent_repository::{
    DataConsentRepository,
    DataConsentPaginationParams,
    DataConsentPaginatedResult,
    DataConsentFilter,
};
pub use data_subject_request_repository::{
    DataSubjectRequestRepository,
    DataSubjectRequestPaginationParams,
    DataSubjectRequestPaginatedResult,
    DataSubjectRequestFilter,
};
pub use employee_repository::{
    EmployeeRepository,
    EmployeePaginationParams,
    EmployeePaginatedResult,
    EmployeeFilter,
};
pub use employee_bank_account_repository::{
    EmployeeBankAccountRepository,
    EmployeeBankAccountPaginationParams,
    EmployeeBankAccountPaginatedResult,
    EmployeeBankAccountFilter,
};
pub use employee_bpjs_repository::{
    EmployeeBpjsRepository,
    EmployeeBpjsPaginationParams,
    EmployeeBpjsPaginatedResult,
    EmployeeBpjsFilter,
};
pub use employee_certification_repository::{
    EmployeeCertificationRepository,
    EmployeeCertificationPaginationParams,
    EmployeeCertificationPaginatedResult,
    EmployeeCertificationFilter,
};
pub use employee_contact_repository::{
    EmployeeContactRepository,
    EmployeeContactPaginationParams,
    EmployeeContactPaginatedResult,
    EmployeeContactFilter,
};
pub use employee_education_repository::{
    EmployeeEducationRepository,
    EmployeeEducationPaginationParams,
    EmployeeEducationPaginatedResult,
    EmployeeEducationFilter,
};
pub use employee_family_repository::{
    EmployeeFamilyRepository,
    EmployeeFamilyPaginationParams,
    EmployeeFamilyPaginatedResult,
    EmployeeFamilyFilter,
};
pub use employee_identity_repository::{
    EmployeeIdentityRepository,
    EmployeeIdentityPaginationParams,
    EmployeeIdentityPaginatedResult,
    EmployeeIdentityFilter,
};
pub use employee_tax_repository::{
    EmployeeTaxRepository,
    EmployeeTaxPaginationParams,
    EmployeeTaxPaginatedResult,
    EmployeeTaxFilter,
};
pub use employee_work_experience_repository::{
    EmployeeWorkExperienceRepository,
    EmployeeWorkExperiencePaginationParams,
    EmployeeWorkExperiencePaginatedResult,
    EmployeeWorkExperienceFilter,
};
pub use employment_repository::{
    EmploymentRepository,
    EmploymentPaginationParams,
    EmploymentPaginatedResult,
    EmploymentFilter,
};
pub use employment_history_repository::{
    EmploymentHistoryRepository,
    EmploymentHistoryPaginationParams,
    EmploymentHistoryPaginatedResult,
    EmploymentHistoryFilter,
};
pub use pii_access_log_repository::{
    PiiAccessLogRepository,
    PiiAccessLogPaginationParams,
    PiiAccessLogPaginatedResult,
    PiiAccessLogFilter,
};
pub use religion_repository::{
    ReligionRepository,
    ReligionPaginationParams,
    ReligionPaginatedResult,
    ReligionFilter,
};
