//! Repository trait for PiiAccessLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PiiAccessLog aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PiiAccessLog, DataCategory};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PiiAccessLogPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PiiAccessLogPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PiiAccessLogPaginatedResult {
    pub data: Vec<PiiAccessLog>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PiiAccessLogFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub accessed_by: Option<Uuid>,
    pub data_category: Option<DataCategory>,
    pub purpose: Option<String>,
}

impl PiiAccessLogFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.accessed_by.is_some() || self.data_category.is_some() || self.purpose.is_some()
    }
}

/// Repository trait for PiiAccessLog aggregate
///
/// This trait defines the persistence contract for PiiAccessLog entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PiiAccessLogRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pii_access_log entity
    async fn save(&self, entity: &PiiAccessLog) -> Result<PiiAccessLog>;

    /// Find pii_access_log by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PiiAccessLog>>;

    /// Find all pii_access_log entities
    async fn find_all(&self) -> Result<Vec<PiiAccessLog>>;

    /// Update pii_access_log by ID
    async fn update(&self, id: &str, entity: &PiiAccessLog) -> Result<Option<PiiAccessLog>>;

    /// Delete pii_access_log by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pii_access_log with pagination
    async fn list(&self, params: PiiAccessLogPaginationParams) -> Result<PiiAccessLogPaginatedResult>;

    /// List pii_access_log with pagination and filters
    async fn list_with_filters(&self, params: PiiAccessLogPaginationParams, filters: PiiAccessLogFilter) -> Result<PiiAccessLogPaginatedResult>;

    /// Count all pii_access_log entities
    async fn count(&self) -> Result<u64>;

    /// Count pii_access_log entities matching filters
    async fn count_with_filters(&self, filters: PiiAccessLogFilter) -> Result<u64>;

    /// Check if pii_access_log exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pii_access_log entities
    async fn bulk_save(&self, entities: &[PiiAccessLog]) -> Result<Vec<PiiAccessLog>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
