//! Repository trait for Religion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Religion aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::Religion;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReligionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ReligionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ReligionPaginatedResult {
    pub data: Vec<Religion>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReligionFilter {
    pub name: Option<String>,
}

impl ReligionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some()
    }
}

/// Repository trait for Religion aggregate
///
/// This trait defines the persistence contract for Religion entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ReligionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new religion entity
    async fn save(&self, entity: &Religion) -> Result<Religion>;

    /// Find religion by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Religion>>;

    /// Find all religion entities
    async fn find_all(&self) -> Result<Vec<Religion>>;

    /// Update religion by ID
    async fn update(&self, id: &str, entity: &Religion) -> Result<Option<Religion>>;

    /// Delete religion by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List religion with pagination
    async fn list(&self, params: ReligionPaginationParams) -> Result<ReligionPaginatedResult>;

    /// List religion with pagination and filters
    async fn list_with_filters(&self, params: ReligionPaginationParams, filters: ReligionFilter) -> Result<ReligionPaginatedResult>;

    /// Count all religion entities
    async fn count(&self) -> Result<u64>;

    /// Count religion entities matching filters
    async fn count_with_filters(&self, filters: ReligionFilter) -> Result<u64>;

    /// Check if religion exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete religion by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted religion by ID
    async fn restore(&self, id: &str) -> Result<Option<Religion>>;

    /// List soft-deleted religion entities
    async fn list_deleted(&self, params: ReligionPaginationParams) -> Result<ReligionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save religion entities
    async fn bulk_save(&self, entities: &[Religion]) -> Result<Vec<Religion>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
