//! Repository for EmployeeContact entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeContact, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeContact;

/// Table name for EmployeeContact entities
pub const TABLE_NAME: &str = "employee.employee_contacts";

/// Repository for EmployeeContact entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeContactRepository(
    backbone_orm::GenericCrudRepository<EmployeeContact, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeContactRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeContact, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeContactRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeContactRepository, EmployeeContact, soft_delete);
