//! Repository for EmployeeEducation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeEducation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeEducation;

/// Table name for EmployeeEducation entities
pub const TABLE_NAME: &str = "employee.employee_educations";

/// Repository for EmployeeEducation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeEducationRepository(
    backbone_orm::GenericCrudRepository<EmployeeEducation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeEducationRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeEducation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeEducationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeEducationRepository, EmployeeEducation, soft_delete);
