//! Repository for EmployeeFamily entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the hand-written PTKP read SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeFamily, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use uuid::Uuid;
use sqlx::{PgPool, Row};

use backbone_orm::org_scope;

use crate::domain::entity::EmployeeFamily;

/// Table name for EmployeeFamily entities
pub const TABLE_NAME: &str = "employee.employee_families";

/// Repository for EmployeeFamily entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeFamilyRepository(
    backbone_orm::GenericCrudRepository<EmployeeFamily, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeFamilyRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeFamily, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeFamilyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written PTKP read SQL. Lives here (not in the query service) per the module's 4-layer rule:
/// services orchestrate, repositories hold the SQL.
impl EmployeeFamilyRepository {
    /// `(spouse_count, child_count)` for `employee_id` — the two inputs to PTKP derivation.
    ///
    /// `spouse_count > 0` ⇒ married (K*); `min(child_count, 3)` ⇒ the tier suffix. A single query
    /// returns both aggregates so the derivation is one round-trip.
    ///
    /// Tenancy (ADR-0029): the module owns no fence — this read rides the AMBIENT org scope via
    /// `org_scope::fetch_optional_row_scoped` (the request-dedicated connection a composing service
    /// scoped), so under a decorated deployment another unit's rows are simply not counted. With no
    /// ambient scope the read runs plainly on the pool — the tenant-agnostic posture of an
    /// undecorated deployment. `employee_id` is a globally unique FK, so the
    /// `WHERE employee_id = $1` filter plus the ambient scope fully isolate the row set — no
    /// explicit tenancy predicate needed. Soft-delete lives in the `metadata` JSONB (`deleted_at` key).
    pub async fn family_counts(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
    ) -> Result<(i64, i64), sqlx::Error> {
        // COUNT always yields exactly one row (0,0 over an empty set), so the row is always
        // present. `relationship = '...'::family_relationship` casts the literal to the enum type.
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT
                     COUNT(*) FILTER (WHERE relationship = 'spouse'::family_relationship)::bigint AS spouse_count,
                     COUNT(*) FILTER (WHERE relationship = 'child'::family_relationship)::bigint AS child_count
                   FROM employee.employee_families
                   WHERE employee_id = $1
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(employee_id),
        )
        .await?;
        row.map(|r| (r.get::<i64, _>("spouse_count"), r.get::<i64, _>("child_count")))
            .ok_or(sqlx::Error::RowNotFound)
    }
}

backbone_core::impl_crud_repository!(EmployeeFamilyRepository, EmployeeFamily, soft_delete);
