//! Repository for EmployeeBpjs entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeBpjs, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeBpjs;

/// Table name for EmployeeBpjs entities
pub const TABLE_NAME: &str = "employee.employee_bpjs";

/// Repository for EmployeeBpjs entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeBpjsRepository(
    backbone_orm::GenericCrudRepository<EmployeeBpjs, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeBpjsRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeBpjs, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeBpjsRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeBpjsRepository, EmployeeBpjs, soft_delete);
