//! Repository for EmploymentHistory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmploymentHistory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmploymentHistory;

/// Table name for EmploymentHistory entities
pub const TABLE_NAME: &str = "employee.employment_histories";

/// Repository for EmploymentHistory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmploymentHistoryRepository(
    backbone_orm::GenericCrudRepository<EmploymentHistory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmploymentHistoryRepository {
    type Target = backbone_orm::GenericCrudRepository<EmploymentHistory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmploymentHistoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmploymentHistoryRepository, EmploymentHistory, soft_delete);
