//! Repository for EmployeeIdentity entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeIdentity, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeIdentity;

/// Table name for EmployeeIdentity entities
pub const TABLE_NAME: &str = "employee.employee_identities";

/// Repository for EmployeeIdentity entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeIdentityRepository(
    backbone_orm::GenericCrudRepository<EmployeeIdentity, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeIdentityRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeIdentity, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeIdentityRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeIdentityRepository, EmployeeIdentity, soft_delete);
