//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod bank_repository;
mod data_consent_repository;
mod data_subject_request_repository;
mod employee_repository;
mod employee_bank_account_repository;
mod employee_bpjs_repository;
mod employee_certification_repository;
mod employee_contact_repository;
mod employee_education_repository;
mod employee_family_repository;
mod employee_identity_repository;
mod employee_tax_repository;
mod employee_work_experience_repository;
mod employment_repository;
mod employment_history_repository;
mod pii_access_log_repository;
mod religion_repository;

// Custom persistence modules
// <<< CUSTOM
pub mod employee_public_repository;
// END CUSTOM

// Re-exports
pub use bank_repository::BankRepository;
pub use data_consent_repository::DataConsentRepository;
pub use data_subject_request_repository::DataSubjectRequestRepository;
pub use employee_repository::EmployeeRepository;
pub use employee_bank_account_repository::EmployeeBankAccountRepository;
pub use employee_bpjs_repository::EmployeeBpjsRepository;
pub use employee_certification_repository::EmployeeCertificationRepository;
pub use employee_contact_repository::EmployeeContactRepository;
pub use employee_education_repository::EmployeeEducationRepository;
pub use employee_family_repository::EmployeeFamilyRepository;
pub use employee_identity_repository::EmployeeIdentityRepository;
pub use employee_tax_repository::EmployeeTaxRepository;
pub use employee_work_experience_repository::EmployeeWorkExperienceRepository;
pub use employment_repository::EmploymentRepository;
pub use employment_history_repository::EmploymentHistoryRepository;
pub use pii_access_log_repository::PiiAccessLogRepository;
pub use religion_repository::ReligionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use employee_public_repository::{EmployeePublicRepository, EmployeePublicRow};
// END CUSTOM