//! Repository for RecordChangeRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RecordChangeRequest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RecordChangeRequest;

/// Table name for RecordChangeRequest entities
pub const TABLE_NAME: &str = "employee.record_change_requests";

/// Repository for RecordChangeRequest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RecordChangeRequestRepository(
    backbone_orm::GenericCrudRepository<RecordChangeRequest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RecordChangeRequestRepository {
    type Target = backbone_orm::GenericCrudRepository<RecordChangeRequest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RecordChangeRequestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RecordChangeRequestRepository, RecordChangeRequest, soft_delete);
