//! Repository for Religion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Religion, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Religion;

/// Table name for Religion entities
pub const TABLE_NAME: &str = "employee.religions";

/// Repository for Religion entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ReligionRepository(
    backbone_orm::GenericCrudRepository<Religion, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ReligionRepository {
    type Target = backbone_orm::GenericCrudRepository<Religion, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ReligionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ReligionRepository, Religion, soft_delete);
