//! Validator for Bank entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Bank>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Bank;

/// Validator type alias for Bank entities.
pub type BankValidator = EntityValidator<Bank>;

/// Build a validator for Bank with all schema-defined field rules.
pub fn bank_validator() -> BankValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Bank| &e.name))
        .rule(OptionalNotBlank::new("code", |e: &Bank| e.code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
