//! Validator for EmployeeBpjs entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EmployeeBpjs>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::EmployeeBpjs;

/// Validator type alias for EmployeeBpjs entities.
pub type EmployeeBpjsValidator = EntityValidator<EmployeeBpjs>;

/// Build a validator for EmployeeBpjs with all schema-defined field rules.
pub fn employee_bpjs_validator() -> EmployeeBpjsValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("bpjs_ketenagakerjaan_number", |e: &EmployeeBpjs| e.bpjs_ketenagakerjaan_number.as_deref()))
        .rule(OptionalNotBlank::new("npp_bpjs_ketenagakerjaan", |e: &EmployeeBpjs| e.npp_bpjs_ketenagakerjaan.as_deref()))
        .rule(OptionalNotBlank::new("bpjs_kesehatan_number", |e: &EmployeeBpjs| e.bpjs_kesehatan_number.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
