//! Validator for EmployeeFamily entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EmployeeFamily>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::EmployeeFamily;

/// Validator type alias for EmployeeFamily entities.
pub type EmployeeFamilyValidator = EntityValidator<EmployeeFamily>;

/// Build a validator for EmployeeFamily with all schema-defined field rules.
pub fn employee_family_validator() -> EmployeeFamilyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &EmployeeFamily| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
