//! Validator for EmployeeEducation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EmployeeEducation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::EmployeeEducation;

/// Validator type alias for EmployeeEducation entities.
pub type EmployeeEducationValidator = EntityValidator<EmployeeEducation>;

/// Build a validator for EmployeeEducation with all schema-defined field rules.
pub fn employee_education_validator() -> EmployeeEducationValidator {
    EntityValidator::new()
        .rule(RequiredString::new("institution_name", |e: &EmployeeEducation| &e.institution_name))
        .rule(OptionalNotBlank::new("major", |e: &EmployeeEducation| e.major.as_deref()))
        .rule(OptionalNotBlank::new("field", |e: &EmployeeEducation| e.field.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
