//! Validator for PiiAccessLog entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PiiAccessLog>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::PiiAccessLog;

/// Validator type alias for PiiAccessLog entities.
pub type PiiAccessLogValidator = EntityValidator<PiiAccessLog>;

/// Build a validator for PiiAccessLog with all schema-defined field rules.
pub fn pii_access_log_validator() -> PiiAccessLogValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("purpose", |e: &PiiAccessLog| e.purpose.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
