//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod bank;
pub mod data_consent;
pub mod data_subject_request;
pub mod employee;
pub mod employee_bank_account;
pub mod employee_bpjs;
pub mod employee_certification;
pub mod employee_contact;
pub mod employee_education;
pub mod employee_family;
pub mod employee_identity;
pub mod employee_tax;
pub mod employee_work_experience;
pub mod employment;
pub mod employment_history;
pub mod pii_access_log;
pub mod religion;
pub mod data_category;
pub mod lawful_basis;
pub mod data_subject_right;
pub mod dsar_status;
pub mod gender;
pub mod marital_status;
pub mod blood_type;
pub mod family_relationship;
pub mod identity_type;
pub mod ptkp_tier;
pub mod tax_method;
pub mod tax_salary;
pub mod employment_status;
pub mod employment_state;
pub mod employment_action;

// Re-exports
pub use bank::Bank;
pub use bank::BankBuilder;
pub use bank::BankId;
pub use data_consent::DataConsent;
pub use data_consent::DataConsentBuilder;
pub use data_consent::DataConsentId;
pub use data_subject_request::DataSubjectRequest;
pub use data_subject_request::DataSubjectRequestBuilder;
pub use data_subject_request::DataSubjectRequestId;
pub use employee::Employee;
pub use employee::EmployeeBuilder;
pub use employee::EmployeeId;
pub use employee_bank_account::EmployeeBankAccount;
pub use employee_bank_account::EmployeeBankAccountBuilder;
pub use employee_bank_account::EmployeeBankAccountId;
pub use employee_bpjs::EmployeeBpjs;
pub use employee_bpjs::EmployeeBpjsBuilder;
pub use employee_bpjs::EmployeeBpjsId;
pub use employee_certification::EmployeeCertification;
pub use employee_certification::EmployeeCertificationBuilder;
pub use employee_certification::EmployeeCertificationId;
pub use employee_contact::EmployeeContact;
pub use employee_contact::EmployeeContactBuilder;
pub use employee_contact::EmployeeContactId;
pub use employee_education::EmployeeEducation;
pub use employee_education::EmployeeEducationBuilder;
pub use employee_education::EmployeeEducationId;
pub use employee_family::EmployeeFamily;
pub use employee_family::EmployeeFamilyBuilder;
pub use employee_family::EmployeeFamilyId;
pub use employee_identity::EmployeeIdentity;
pub use employee_identity::EmployeeIdentityBuilder;
pub use employee_identity::EmployeeIdentityId;
pub use employee_tax::EmployeeTax;
pub use employee_tax::EmployeeTaxBuilder;
pub use employee_tax::EmployeeTaxId;
pub use employee_work_experience::EmployeeWorkExperience;
pub use employee_work_experience::EmployeeWorkExperienceBuilder;
pub use employee_work_experience::EmployeeWorkExperienceId;
pub use employment::Employment;
pub use employment::EmploymentBuilder;
pub use employment::EmploymentId;
pub use employment_history::EmploymentHistory;
pub use employment_history::EmploymentHistoryBuilder;
pub use employment_history::EmploymentHistoryId;
pub use pii_access_log::PiiAccessLog;
pub use pii_access_log::PiiAccessLogBuilder;
pub use pii_access_log::PiiAccessLogId;
pub use religion::Religion;
pub use religion::ReligionBuilder;
pub use religion::ReligionId;
pub use data_category::DataCategory;
pub use lawful_basis::LawfulBasis;
pub use data_subject_right::DataSubjectRight;
pub use dsar_status::DsarStatus;
pub use gender::Gender;
pub use marital_status::MaritalStatus;
pub use blood_type::BloodType;
pub use family_relationship::FamilyRelationship;
pub use identity_type::IdentityType;
pub use ptkp_tier::PtkpTier;
pub use tax_method::TaxMethod;
pub use tax_salary::TaxSalary;
pub use employment_status::EmploymentStatus;
pub use employment_state::EmploymentState;
pub use employment_action::EmploymentAction;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
