//! Auth configuration for Bank handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Bank>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BankService;
use crate::domain::entity::Bank;

/// Permission string constants for Bank operations.
pub mod permissions {
    pub const LIST:        &str = "bank:list";
    pub const READ:        &str = "bank:read";
    pub const CREATE:      &str = "bank:create";
    pub const UPDATE:      &str = "bank:update";
    pub const DELETE:      &str = "bank:delete";
    pub const RESTORE:     &str = "bank:restore";
    pub const TRASH:       &str = "bank:trash";
    pub const EMPTY_TRASH: &str = "bank:empty_trash";
    pub const BULK_CREATE: &str = "bank:bulk_create";
    pub const UPSERT:      &str = "bank:upsert";
}

/// Resource policy for Bank — maps CRUD actions to permission strings.
pub struct BankPolicy;

#[async_trait]
impl ResourcePolicy<Bank> for BankPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Bank,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Bank handlers.
///
/// Wraps `BankService` and checks `BankPolicy` before delegating.
pub type BankGuard = PermissionGuard<Bank>;

/// Service-integrated permission guard for Bank (for use in generated handlers).
pub type BankServiceGuard = ServicePermissionGuard<Bank, BankService, BankPolicy>;

// <<< CUSTOM
// END CUSTOM
