//! Auth configuration for EmployeeEducation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeEducation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeEducationService;
use crate::domain::entity::EmployeeEducation;

/// Permission string constants for EmployeeEducation operations.
pub mod permissions {
    pub const LIST:        &str = "employee_education:list";
    pub const READ:        &str = "employee_education:read";
    pub const CREATE:      &str = "employee_education:create";
    pub const UPDATE:      &str = "employee_education:update";
    pub const DELETE:      &str = "employee_education:delete";
    pub const RESTORE:     &str = "employee_education:restore";
    pub const TRASH:       &str = "employee_education:trash";
    pub const EMPTY_TRASH: &str = "employee_education:empty_trash";
    pub const BULK_CREATE: &str = "employee_education:bulk_create";
    pub const UPSERT:      &str = "employee_education:upsert";
}

/// Resource policy for EmployeeEducation — maps CRUD actions to permission strings.
pub struct EmployeeEducationPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeEducation> for EmployeeEducationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeEducation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeEducation handlers.
///
/// Wraps `EmployeeEducationService` and checks `EmployeeEducationPolicy` before delegating.
pub type EmployeeEducationGuard = PermissionGuard<EmployeeEducation>;

/// Service-integrated permission guard for EmployeeEducation (for use in generated handlers).
pub type EmployeeEducationServiceGuard = ServicePermissionGuard<EmployeeEducation, EmployeeEducationService, EmployeeEducationPolicy>;

// <<< CUSTOM
// END CUSTOM
