//! Auth configuration for EmployeeTax handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeTax>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeTaxService;
use crate::domain::entity::EmployeeTax;

/// Permission string constants for EmployeeTax operations.
pub mod permissions {
    pub const LIST:        &str = "employee_tax:list";
    pub const READ:        &str = "employee_tax:read";
    pub const CREATE:      &str = "employee_tax:create";
    pub const UPDATE:      &str = "employee_tax:update";
    pub const DELETE:      &str = "employee_tax:delete";
    pub const RESTORE:     &str = "employee_tax:restore";
    pub const TRASH:       &str = "employee_tax:trash";
    pub const EMPTY_TRASH: &str = "employee_tax:empty_trash";
    pub const BULK_CREATE: &str = "employee_tax:bulk_create";
    pub const UPSERT:      &str = "employee_tax:upsert";
}

/// Resource policy for EmployeeTax — maps CRUD actions to permission strings.
pub struct EmployeeTaxPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeTax> for EmployeeTaxPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeTax,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeTax handlers.
///
/// Wraps `EmployeeTaxService` and checks `EmployeeTaxPolicy` before delegating.
pub type EmployeeTaxGuard = PermissionGuard<EmployeeTax>;

/// Service-integrated permission guard for EmployeeTax (for use in generated handlers).
pub type EmployeeTaxServiceGuard = ServicePermissionGuard<EmployeeTax, EmployeeTaxService, EmployeeTaxPolicy>;

// <<< CUSTOM
// END CUSTOM
