//! Auth configuration for EmployeeBpjs handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeBpjs>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeBpjsService;
use crate::domain::entity::EmployeeBpjs;

/// Permission string constants for EmployeeBpjs operations.
pub mod permissions {
    pub const LIST:        &str = "employee_bpjs:list";
    pub const READ:        &str = "employee_bpjs:read";
    pub const CREATE:      &str = "employee_bpjs:create";
    pub const UPDATE:      &str = "employee_bpjs:update";
    pub const DELETE:      &str = "employee_bpjs:delete";
    pub const RESTORE:     &str = "employee_bpjs:restore";
    pub const TRASH:       &str = "employee_bpjs:trash";
    pub const EMPTY_TRASH: &str = "employee_bpjs:empty_trash";
    pub const BULK_CREATE: &str = "employee_bpjs:bulk_create";
    pub const UPSERT:      &str = "employee_bpjs:upsert";
}

/// Resource policy for EmployeeBpjs — maps CRUD actions to permission strings.
pub struct EmployeeBpjsPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeBpjs> for EmployeeBpjsPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeBpjs,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeBpjs handlers.
///
/// Wraps `EmployeeBpjsService` and checks `EmployeeBpjsPolicy` before delegating.
pub type EmployeeBpjsGuard = PermissionGuard<EmployeeBpjs>;

/// Service-integrated permission guard for EmployeeBpjs (for use in generated handlers).
pub type EmployeeBpjsServiceGuard = ServicePermissionGuard<EmployeeBpjs, EmployeeBpjsService, EmployeeBpjsPolicy>;

// <<< CUSTOM
// END CUSTOM
