//! Auth configuration for EmployeeWorkExperience handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeWorkExperience>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeWorkExperienceService;
use crate::domain::entity::EmployeeWorkExperience;

/// Permission string constants for EmployeeWorkExperience operations.
pub mod permissions {
    pub const LIST:        &str = "employee_work_experience:list";
    pub const READ:        &str = "employee_work_experience:read";
    pub const CREATE:      &str = "employee_work_experience:create";
    pub const UPDATE:      &str = "employee_work_experience:update";
    pub const DELETE:      &str = "employee_work_experience:delete";
    pub const RESTORE:     &str = "employee_work_experience:restore";
    pub const TRASH:       &str = "employee_work_experience:trash";
    pub const EMPTY_TRASH: &str = "employee_work_experience:empty_trash";
    pub const BULK_CREATE: &str = "employee_work_experience:bulk_create";
    pub const UPSERT:      &str = "employee_work_experience:upsert";
}

/// Resource policy for EmployeeWorkExperience — maps CRUD actions to permission strings.
pub struct EmployeeWorkExperiencePolicy;

#[async_trait]
impl ResourcePolicy<EmployeeWorkExperience> for EmployeeWorkExperiencePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeWorkExperience,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeWorkExperience handlers.
///
/// Wraps `EmployeeWorkExperienceService` and checks `EmployeeWorkExperiencePolicy` before delegating.
pub type EmployeeWorkExperienceGuard = PermissionGuard<EmployeeWorkExperience>;

/// Service-integrated permission guard for EmployeeWorkExperience (for use in generated handlers).
pub type EmployeeWorkExperienceServiceGuard = ServicePermissionGuard<EmployeeWorkExperience, EmployeeWorkExperienceService, EmployeeWorkExperiencePolicy>;

// <<< CUSTOM
// END CUSTOM
