//! Auth configuration for Employment handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Employment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmploymentService;
use crate::domain::entity::Employment;

/// Permission string constants for Employment operations.
pub mod permissions {
    pub const LIST:        &str = "employment:list";
    pub const READ:        &str = "employment:read";
    pub const CREATE:      &str = "employment:create";
    pub const UPDATE:      &str = "employment:update";
    pub const DELETE:      &str = "employment:delete";
    pub const RESTORE:     &str = "employment:restore";
    pub const TRASH:       &str = "employment:trash";
    pub const EMPTY_TRASH: &str = "employment:empty_trash";
    pub const BULK_CREATE: &str = "employment:bulk_create";
    pub const UPSERT:      &str = "employment:upsert";
}

/// Resource policy for Employment — maps CRUD actions to permission strings.
pub struct EmploymentPolicy;

#[async_trait]
impl ResourcePolicy<Employment> for EmploymentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Employment,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Employment handlers.
///
/// Wraps `EmploymentService` and checks `EmploymentPolicy` before delegating.
pub type EmploymentGuard = PermissionGuard<Employment>;

/// Service-integrated permission guard for Employment (for use in generated handlers).
pub type EmploymentServiceGuard = ServicePermissionGuard<Employment, EmploymentService, EmploymentPolicy>;

// <<< CUSTOM
// END CUSTOM
