//! Auth configuration for EmployeeCertification handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeCertification>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeCertificationService;
use crate::domain::entity::EmployeeCertification;

/// Permission string constants for EmployeeCertification operations.
pub mod permissions {
    pub const LIST:        &str = "employee_certification:list";
    pub const READ:        &str = "employee_certification:read";
    pub const CREATE:      &str = "employee_certification:create";
    pub const UPDATE:      &str = "employee_certification:update";
    pub const DELETE:      &str = "employee_certification:delete";
    pub const RESTORE:     &str = "employee_certification:restore";
    pub const TRASH:       &str = "employee_certification:trash";
    pub const EMPTY_TRASH: &str = "employee_certification:empty_trash";
    pub const BULK_CREATE: &str = "employee_certification:bulk_create";
    pub const UPSERT:      &str = "employee_certification:upsert";
}

/// Resource policy for EmployeeCertification — maps CRUD actions to permission strings.
pub struct EmployeeCertificationPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeCertification> for EmployeeCertificationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeCertification,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeCertification handlers.
///
/// Wraps `EmployeeCertificationService` and checks `EmployeeCertificationPolicy` before delegating.
pub type EmployeeCertificationGuard = PermissionGuard<EmployeeCertification>;

/// Service-integrated permission guard for EmployeeCertification (for use in generated handlers).
pub type EmployeeCertificationServiceGuard = ServicePermissionGuard<EmployeeCertification, EmployeeCertificationService, EmployeeCertificationPolicy>;

// <<< CUSTOM
// END CUSTOM
