//! Auth configuration for EmployeeBankAccount handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeBankAccount>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeBankAccountService;
use crate::domain::entity::EmployeeBankAccount;

/// Permission string constants for EmployeeBankAccount operations.
pub mod permissions {
    pub const LIST:        &str = "employee_bank_account:list";
    pub const READ:        &str = "employee_bank_account:read";
    pub const CREATE:      &str = "employee_bank_account:create";
    pub const UPDATE:      &str = "employee_bank_account:update";
    pub const DELETE:      &str = "employee_bank_account:delete";
    pub const RESTORE:     &str = "employee_bank_account:restore";
    pub const TRASH:       &str = "employee_bank_account:trash";
    pub const EMPTY_TRASH: &str = "employee_bank_account:empty_trash";
    pub const BULK_CREATE: &str = "employee_bank_account:bulk_create";
    pub const UPSERT:      &str = "employee_bank_account:upsert";
}

/// Resource policy for EmployeeBankAccount — maps CRUD actions to permission strings.
pub struct EmployeeBankAccountPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeBankAccount> for EmployeeBankAccountPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeBankAccount,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeBankAccount handlers.
///
/// Wraps `EmployeeBankAccountService` and checks `EmployeeBankAccountPolicy` before delegating.
pub type EmployeeBankAccountGuard = PermissionGuard<EmployeeBankAccount>;

/// Service-integrated permission guard for EmployeeBankAccount (for use in generated handlers).
pub type EmployeeBankAccountServiceGuard = ServicePermissionGuard<EmployeeBankAccount, EmployeeBankAccountService, EmployeeBankAccountPolicy>;

// <<< CUSTOM
// END CUSTOM
