//! Auth configuration for Example handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Example>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ExampleService;
use crate::domain::entity::Example;

/// Permission string constants for Example operations.
pub mod permissions {
    pub const LIST:        &str = "example:list";
    pub const READ:        &str = "example:read";
    pub const CREATE:      &str = "example:create";
    pub const UPDATE:      &str = "example:update";
    pub const DELETE:      &str = "example:delete";
    pub const RESTORE:     &str = "example:restore";
    pub const TRASH:       &str = "example:trash";
    pub const EMPTY_TRASH: &str = "example:empty_trash";
    pub const BULK_CREATE: &str = "example:bulk_create";
    pub const UPSERT:      &str = "example:upsert";
}

/// Resource policy for Example — maps CRUD actions to permission strings.
pub struct ExamplePolicy;

#[async_trait]
impl ResourcePolicy<Example> for ExamplePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Example,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Example handlers.
///
/// Wraps `ExampleService` and checks `ExamplePolicy` before delegating.
pub type ExampleGuard = PermissionGuard<Example>;

/// Service-integrated permission guard for Example (for use in generated handlers).
pub type ExampleServiceGuard = ServicePermissionGuard<Example, ExampleService, ExamplePolicy>;

// <<< CUSTOM
// END CUSTOM
