//! DataConsent API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the DataConsent CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DATACONSENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for DataConsent
pub struct DataConsentTestData;

impl TestDataGenerator for DataConsentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "data_category": "identity",
            "lawful_basis": "consent",
            "consent_given_at": now,
            "consent_method": null,
            "privacy_notice_version": null,
            "retention_until": null,
            "withdrawn_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "data_category": "identity",
            "lawful_basis": "consent",
            "consent_given_at": now,
            "consent_method": null,
            "privacy_notice_version": null,
            "retention_until": null,
            "withdrawn_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/employees", &super::employee_api_test::EmployeeTestData).await {
            deps.push(("employee_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// DATACONSENT API TEST
// ============================================================================

/// DataConsent API test suite
pub struct DataConsentApiTest {
    inner: GenericCrudTest<DataConsentTestData>,
}

impl DataConsentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/data_consents", "DataConsent");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DataConsentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DataConsentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_data_consent_crud() {
        let mut test = DataConsentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add DataConsent specific tests here
// <<< CUSTOM TESTS END >>>
