//! EmployeeBpjs API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EmployeeBpjs CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EMPLOYEEBPJS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EmployeeBpjs
pub struct EmployeeBpjsTestData;

impl TestDataGenerator for EmployeeBpjsTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "bpjs_ketenagakerjaan_number": null,
            "npp_bpjs_ketenagakerjaan": null,
            "bpjs_ketenagakerjaan_date": null,
            "bpjs_kesehatan_number": null,
            "bpjs_kesehatan_family": null,
            "bpjs_kesehatan_date": null,
            "jaminan_pensiun_date": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "bpjs_ketenagakerjaan_number": null,
            "npp_bpjs_ketenagakerjaan": null,
            "bpjs_ketenagakerjaan_date": null,
            "bpjs_kesehatan_number": null,
            "bpjs_kesehatan_family": null,
            "bpjs_kesehatan_date": null,
            "jaminan_pensiun_date": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/employees", &super::employee_api_test::EmployeeTestData).await {
            deps.push(("employee_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// EMPLOYEEBPJS API TEST
// ============================================================================

/// EmployeeBpjs API test suite
pub struct EmployeeBpjsApiTest {
    inner: GenericCrudTest<EmployeeBpjsTestData>,
}

impl EmployeeBpjsApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/employee_bpjs", "EmployeeBpjs");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EmployeeBpjsTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EmployeeBpjsApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_employee_bpjs_crud() {
        let mut test = EmployeeBpjsApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EmployeeBpjs specific tests here
// <<< CUSTOM TESTS END >>>
