//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod bank_api_test;
pub mod data_consent_api_test;
pub mod data_subject_request_api_test;
pub mod employee_api_test;
pub mod employee_bank_account_api_test;
pub mod employee_bpjs_api_test;
pub mod employee_certification_api_test;
pub mod employee_contact_api_test;
pub mod employee_education_api_test;
pub mod employee_family_api_test;
pub mod employee_identity_api_test;
pub mod employee_tax_api_test;
pub mod employee_work_experience_api_test;
pub mod employment_api_test;
pub mod employment_history_api_test;
pub mod pii_access_log_api_test;
pub mod religion_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use bank_api_test::*;
pub use data_consent_api_test::*;
pub use data_subject_request_api_test::*;
pub use employee_api_test::*;
pub use employee_bank_account_api_test::*;
pub use employee_bpjs_api_test::*;
pub use employee_certification_api_test::*;
pub use employee_contact_api_test::*;
pub use employee_education_api_test::*;
pub use employee_family_api_test::*;
pub use employee_identity_api_test::*;
pub use employee_tax_api_test::*;
pub use employee_work_experience_api_test::*;
pub use employment_api_test::*;
pub use employment_history_api_test::*;
pub use pii_access_log_api_test::*;
pub use religion_api_test::*;
