//! RecordChangeRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the RecordChangeRequest CRUD API endpoints.

use chrono::Utc;
use crate::integration::framework::ApiTest;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// RECORDCHANGEREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for RecordChangeRequest
pub struct RecordChangeRequestTestData;

impl TestDataGenerator for RecordChangeRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "field_path": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "current_value": null,
            "proposed_value": null,
            "reason": null,
            "status": "pending",
            "approval_request_id": null,
            "decided_at": now,
            "applied_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "field_path": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "current_value": null,
            "proposed_value": null,
            "reason": null,
            "status": "pending",
            "approval_request_id": null,
            "decided_at": now,
            "applied_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/employees", &super::employee_api_test::EmployeeTestData).await {
            deps.push(("employee_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// RECORDCHANGEREQUEST API TEST
// ============================================================================

/// RecordChangeRequest API test suite
pub struct RecordChangeRequestApiTest {
    inner: GenericCrudTest<RecordChangeRequestTestData>,
}

impl RecordChangeRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/record_change_requests", "RecordChangeRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RecordChangeRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RecordChangeRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_record_change_request_crud() {
        let mut test = RecordChangeRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add RecordChangeRequest specific tests here
// <<< CUSTOM TESTS END >>>
