//! Employee Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::BankService;
use crate::application::service::DataConsentService;
use crate::application::service::DataSubjectRequestService;
use crate::application::service::EmployeeService;
use crate::application::service::EmployeeBankAccountService;
use crate::application::service::EmployeeBpjsService;
use crate::application::service::EmployeeCertificationService;
use crate::application::service::EmployeeContactService;
use crate::application::service::EmployeeEducationService;
use crate::application::service::EmployeeFamilyService;
use crate::application::service::EmployeeIdentityService;
use crate::application::service::EmployeeTaxService;
use crate::application::service::EmployeeWorkExperienceService;
use crate::application::service::EmploymentService;
use crate::application::service::EmploymentHistoryService;
use crate::application::service::PiiAccessLogService;
use crate::application::service::ReligionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Bank service
    pub bank_service: Arc<BankService>,
    /// DataConsent service
    pub data_consent_service: Arc<DataConsentService>,
    /// DataSubjectRequest service
    pub data_subject_request_service: Arc<DataSubjectRequestService>,
    /// Employee service
    pub employee_service: Arc<EmployeeService>,
    /// EmployeeBankAccount service
    pub employee_bank_account_service: Arc<EmployeeBankAccountService>,
    /// EmployeeBpjs service
    pub employee_bpjs_service: Arc<EmployeeBpjsService>,
    /// EmployeeCertification service
    pub employee_certification_service: Arc<EmployeeCertificationService>,
    /// EmployeeContact service
    pub employee_contact_service: Arc<EmployeeContactService>,
    /// EmployeeEducation service
    pub employee_education_service: Arc<EmployeeEducationService>,
    /// EmployeeFamily service
    pub employee_family_service: Arc<EmployeeFamilyService>,
    /// EmployeeIdentity service
    pub employee_identity_service: Arc<EmployeeIdentityService>,
    /// EmployeeTax service
    pub employee_tax_service: Arc<EmployeeTaxService>,
    /// EmployeeWorkExperience service
    pub employee_work_experience_service: Arc<EmployeeWorkExperienceService>,
    /// Employment service
    pub employment_service: Arc<EmploymentService>,
    /// EmploymentHistory service
    pub employment_history_service: Arc<EmploymentHistoryService>,
    /// PiiAccessLog service
    pub pii_access_log_service: Arc<PiiAccessLogService>,
    /// Religion service
    pub religion_service: Arc<ReligionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        bank_service: Arc<BankService>,
        data_consent_service: Arc<DataConsentService>,
        data_subject_request_service: Arc<DataSubjectRequestService>,
        employee_service: Arc<EmployeeService>,
        employee_bank_account_service: Arc<EmployeeBankAccountService>,
        employee_bpjs_service: Arc<EmployeeBpjsService>,
        employee_certification_service: Arc<EmployeeCertificationService>,
        employee_contact_service: Arc<EmployeeContactService>,
        employee_education_service: Arc<EmployeeEducationService>,
        employee_family_service: Arc<EmployeeFamilyService>,
        employee_identity_service: Arc<EmployeeIdentityService>,
        employee_tax_service: Arc<EmployeeTaxService>,
        employee_work_experience_service: Arc<EmployeeWorkExperienceService>,
        employment_service: Arc<EmploymentService>,
        employment_history_service: Arc<EmploymentHistoryService>,
        pii_access_log_service: Arc<PiiAccessLogService>,
        religion_service: Arc<ReligionService>
    ) -> Self {
        Self {
            bank_service,
            data_consent_service,
            data_subject_request_service,
            employee_service,
            employee_bank_account_service,
            employee_bpjs_service,
            employee_certification_service,
            employee_contact_service,
            employee_education_service,
            employee_family_service,
            employee_identity_service,
            employee_tax_service,
            employee_work_experience_service,
            employment_service,
            employment_history_service,
            pii_access_log_service,
            religion_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::EmployeeModule) -> Self {
        Self {
            bank_service: module.bank_service.clone(),
            data_consent_service: module.data_consent_service.clone(),
            data_subject_request_service: module.data_subject_request_service.clone(),
            employee_service: module.employee_service.clone(),
            employee_bank_account_service: module.employee_bank_account_service.clone(),
            employee_bpjs_service: module.employee_bpjs_service.clone(),
            employee_certification_service: module.employee_certification_service.clone(),
            employee_contact_service: module.employee_contact_service.clone(),
            employee_education_service: module.employee_education_service.clone(),
            employee_family_service: module.employee_family_service.clone(),
            employee_identity_service: module.employee_identity_service.clone(),
            employee_tax_service: module.employee_tax_service.clone(),
            employee_work_experience_service: module.employee_work_experience_service.clone(),
            employment_service: module.employment_service.clone(),
            employment_history_service: module.employment_history_service.clone(),
            pii_access_log_service: module.pii_access_log_service.clone(),
            religion_service: module.religion_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    bank_service: Option<Arc<BankService>>,
    data_consent_service: Option<Arc<DataConsentService>>,
    data_subject_request_service: Option<Arc<DataSubjectRequestService>>,
    employee_service: Option<Arc<EmployeeService>>,
    employee_bank_account_service: Option<Arc<EmployeeBankAccountService>>,
    employee_bpjs_service: Option<Arc<EmployeeBpjsService>>,
    employee_certification_service: Option<Arc<EmployeeCertificationService>>,
    employee_contact_service: Option<Arc<EmployeeContactService>>,
    employee_education_service: Option<Arc<EmployeeEducationService>>,
    employee_family_service: Option<Arc<EmployeeFamilyService>>,
    employee_identity_service: Option<Arc<EmployeeIdentityService>>,
    employee_tax_service: Option<Arc<EmployeeTaxService>>,
    employee_work_experience_service: Option<Arc<EmployeeWorkExperienceService>>,
    employment_service: Option<Arc<EmploymentService>>,
    employment_history_service: Option<Arc<EmploymentHistoryService>>,
    pii_access_log_service: Option<Arc<PiiAccessLogService>>,
    religion_service: Option<Arc<ReligionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Bank service.
    pub fn with_bank_service(mut self, service: Arc<BankService>) -> Self {
        self.bank_service = Some(service);
        self
    }

    /// Set the DataConsent service.
    pub fn with_data_consent_service(mut self, service: Arc<DataConsentService>) -> Self {
        self.data_consent_service = Some(service);
        self
    }

    /// Set the DataSubjectRequest service.
    pub fn with_data_subject_request_service(mut self, service: Arc<DataSubjectRequestService>) -> Self {
        self.data_subject_request_service = Some(service);
        self
    }

    /// Set the Employee service.
    pub fn with_employee_service(mut self, service: Arc<EmployeeService>) -> Self {
        self.employee_service = Some(service);
        self
    }

    /// Set the EmployeeBankAccount service.
    pub fn with_employee_bank_account_service(mut self, service: Arc<EmployeeBankAccountService>) -> Self {
        self.employee_bank_account_service = Some(service);
        self
    }

    /// Set the EmployeeBpjs service.
    pub fn with_employee_bpjs_service(mut self, service: Arc<EmployeeBpjsService>) -> Self {
        self.employee_bpjs_service = Some(service);
        self
    }

    /// Set the EmployeeCertification service.
    pub fn with_employee_certification_service(mut self, service: Arc<EmployeeCertificationService>) -> Self {
        self.employee_certification_service = Some(service);
        self
    }

    /// Set the EmployeeContact service.
    pub fn with_employee_contact_service(mut self, service: Arc<EmployeeContactService>) -> Self {
        self.employee_contact_service = Some(service);
        self
    }

    /// Set the EmployeeEducation service.
    pub fn with_employee_education_service(mut self, service: Arc<EmployeeEducationService>) -> Self {
        self.employee_education_service = Some(service);
        self
    }

    /// Set the EmployeeFamily service.
    pub fn with_employee_family_service(mut self, service: Arc<EmployeeFamilyService>) -> Self {
        self.employee_family_service = Some(service);
        self
    }

    /// Set the EmployeeIdentity service.
    pub fn with_employee_identity_service(mut self, service: Arc<EmployeeIdentityService>) -> Self {
        self.employee_identity_service = Some(service);
        self
    }

    /// Set the EmployeeTax service.
    pub fn with_employee_tax_service(mut self, service: Arc<EmployeeTaxService>) -> Self {
        self.employee_tax_service = Some(service);
        self
    }

    /// Set the EmployeeWorkExperience service.
    pub fn with_employee_work_experience_service(mut self, service: Arc<EmployeeWorkExperienceService>) -> Self {
        self.employee_work_experience_service = Some(service);
        self
    }

    /// Set the Employment service.
    pub fn with_employment_service(mut self, service: Arc<EmploymentService>) -> Self {
        self.employment_service = Some(service);
        self
    }

    /// Set the EmploymentHistory service.
    pub fn with_employment_history_service(mut self, service: Arc<EmploymentHistoryService>) -> Self {
        self.employment_history_service = Some(service);
        self
    }

    /// Set the PiiAccessLog service.
    pub fn with_pii_access_log_service(mut self, service: Arc<PiiAccessLogService>) -> Self {
        self.pii_access_log_service = Some(service);
        self
    }

    /// Set the Religion service.
    pub fn with_religion_service(mut self, service: Arc<ReligionService>) -> Self {
        self.religion_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            bank_service: self.bank_service.expect("bank_service is required"),
            data_consent_service: self.data_consent_service.expect("data_consent_service is required"),
            data_subject_request_service: self.data_subject_request_service.expect("data_subject_request_service is required"),
            employee_service: self.employee_service.expect("employee_service is required"),
            employee_bank_account_service: self.employee_bank_account_service.expect("employee_bank_account_service is required"),
            employee_bpjs_service: self.employee_bpjs_service.expect("employee_bpjs_service is required"),
            employee_certification_service: self.employee_certification_service.expect("employee_certification_service is required"),
            employee_contact_service: self.employee_contact_service.expect("employee_contact_service is required"),
            employee_education_service: self.employee_education_service.expect("employee_education_service is required"),
            employee_family_service: self.employee_family_service.expect("employee_family_service is required"),
            employee_identity_service: self.employee_identity_service.expect("employee_identity_service is required"),
            employee_tax_service: self.employee_tax_service.expect("employee_tax_service is required"),
            employee_work_experience_service: self.employee_work_experience_service.expect("employee_work_experience_service is required"),
            employment_service: self.employment_service.expect("employment_service is required"),
            employment_history_service: self.employment_history_service.expect("employment_history_service is required"),
            pii_access_log_service: self.pii_access_log_service.expect("pii_access_log_service is required"),
            religion_service: self.religion_service.expect("religion_service is required"),
        }
    }
}
