//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    bank_handler::create_bank_routes,
    data_consent_handler::create_data_consent_routes,
    data_subject_request_handler::create_data_subject_request_routes,
    employee_handler::create_employee_routes,
    employee_bank_account_handler::create_employee_bank_account_routes,
    employee_bpjs_handler::create_employee_bpjs_routes,
    employee_certification_handler::create_employee_certification_routes,
    employee_contact_handler::create_employee_contact_routes,
    employee_education_handler::create_employee_education_routes,
    employee_family_handler::create_employee_family_routes,
    employee_identity_handler::create_employee_identity_routes,
    employee_tax_handler::create_employee_tax_routes,
    employee_work_experience_handler::create_employee_work_experience_routes,
    employment_handler::create_employment_routes,
    employment_history_handler::create_employment_history_routes,
    pii_access_log_handler::create_pii_access_log_routes,
    religion_handler::create_religion_routes,
};

use crate::application::service::{
    BankService,
    DataConsentService,
    DataSubjectRequestService,
    EmployeeService,
    EmployeeBankAccountService,
    EmployeeBpjsService,
    EmployeeCertificationService,
    EmployeeContactService,
    EmployeeEducationService,
    EmployeeFamilyService,
    EmployeeIdentityService,
    EmployeeTaxService,
    EmployeeWorkExperienceService,
    EmploymentService,
    EmploymentHistoryService,
    PiiAccessLogService,
    ReligionService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub bank: Arc<BankService>,
    pub data_consent: Arc<DataConsentService>,
    pub data_subject_request: Arc<DataSubjectRequestService>,
    pub employee: Arc<EmployeeService>,
    pub employee_bank_account: Arc<EmployeeBankAccountService>,
    pub employee_bpjs: Arc<EmployeeBpjsService>,
    pub employee_certification: Arc<EmployeeCertificationService>,
    pub employee_contact: Arc<EmployeeContactService>,
    pub employee_education: Arc<EmployeeEducationService>,
    pub employee_family: Arc<EmployeeFamilyService>,
    pub employee_identity: Arc<EmployeeIdentityService>,
    pub employee_tax: Arc<EmployeeTaxService>,
    pub employee_work_experience: Arc<EmployeeWorkExperienceService>,
    pub employment: Arc<EmploymentService>,
    pub employment_history: Arc<EmploymentHistoryService>,
    pub pii_access_log: Arc<PiiAccessLogService>,
    pub religion: Arc<ReligionService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Bank routes (12 Backbone endpoints)
        .merge(create_bank_routes(services.bank))
        // DataConsent routes (12 Backbone endpoints)
        .merge(create_data_consent_routes(services.data_consent))
        // DataSubjectRequest routes (12 Backbone endpoints)
        .merge(create_data_subject_request_routes(services.data_subject_request))
        // Employee routes (12 Backbone endpoints)
        .merge(create_employee_routes(services.employee))
        // EmployeeBankAccount routes (12 Backbone endpoints)
        .merge(create_employee_bank_account_routes(services.employee_bank_account))
        // EmployeeBpjs routes (12 Backbone endpoints)
        .merge(create_employee_bpjs_routes(services.employee_bpjs))
        // EmployeeCertification routes (12 Backbone endpoints)
        .merge(create_employee_certification_routes(services.employee_certification))
        // EmployeeContact routes (12 Backbone endpoints)
        .merge(create_employee_contact_routes(services.employee_contact))
        // EmployeeEducation routes (12 Backbone endpoints)
        .merge(create_employee_education_routes(services.employee_education))
        // EmployeeFamily routes (12 Backbone endpoints)
        .merge(create_employee_family_routes(services.employee_family))
        // EmployeeIdentity routes (12 Backbone endpoints)
        .merge(create_employee_identity_routes(services.employee_identity))
        // EmployeeTax routes (12 Backbone endpoints)
        .merge(create_employee_tax_routes(services.employee_tax))
        // EmployeeWorkExperience routes (12 Backbone endpoints)
        .merge(create_employee_work_experience_routes(services.employee_work_experience))
        // Employment routes (12 Backbone endpoints)
        .merge(create_employment_routes(services.employment))
        // EmploymentHistory routes (12 Backbone endpoints)
        .merge(create_employment_history_routes(services.employment_history))
        // PiiAccessLog routes (12 Backbone endpoints)
        .merge(create_pii_access_log_routes(services.pii_access_log))
        // Religion routes (12 Backbone endpoints)
        .merge(create_religion_routes(services.religion))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn bank_routes(service: Arc<BankService>) -> Router {
        create_bank_routes(service)
    }

    pub fn data_consent_routes(service: Arc<DataConsentService>) -> Router {
        create_data_consent_routes(service)
    }

    pub fn data_subject_request_routes(service: Arc<DataSubjectRequestService>) -> Router {
        create_data_subject_request_routes(service)
    }

    pub fn employee_routes(service: Arc<EmployeeService>) -> Router {
        create_employee_routes(service)
    }

    pub fn employee_bank_account_routes(service: Arc<EmployeeBankAccountService>) -> Router {
        create_employee_bank_account_routes(service)
    }

    pub fn employee_bpjs_routes(service: Arc<EmployeeBpjsService>) -> Router {
        create_employee_bpjs_routes(service)
    }

    pub fn employee_certification_routes(service: Arc<EmployeeCertificationService>) -> Router {
        create_employee_certification_routes(service)
    }

    pub fn employee_contact_routes(service: Arc<EmployeeContactService>) -> Router {
        create_employee_contact_routes(service)
    }

    pub fn employee_education_routes(service: Arc<EmployeeEducationService>) -> Router {
        create_employee_education_routes(service)
    }

    pub fn employee_family_routes(service: Arc<EmployeeFamilyService>) -> Router {
        create_employee_family_routes(service)
    }

    pub fn employee_identity_routes(service: Arc<EmployeeIdentityService>) -> Router {
        create_employee_identity_routes(service)
    }

    pub fn employee_tax_routes(service: Arc<EmployeeTaxService>) -> Router {
        create_employee_tax_routes(service)
    }

    pub fn employee_work_experience_routes(service: Arc<EmployeeWorkExperienceService>) -> Router {
        create_employee_work_experience_routes(service)
    }

    pub fn employment_routes(service: Arc<EmploymentService>) -> Router {
        create_employment_routes(service)
    }

    pub fn employment_history_routes(service: Arc<EmploymentHistoryService>) -> Router {
        create_employment_history_routes(service)
    }

    pub fn pii_access_log_routes(service: Arc<PiiAccessLogService>) -> Router {
        create_pii_access_log_routes(service)
    }

    pub fn religion_routes(service: Arc<ReligionService>) -> Router {
        create_religion_routes(service)
    }

}
