//! Employee Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Employee exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use employee::exports::{BankDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `BankDto` - Data transfer object for Bank
/// - `BankSummary` - Summary view of Bank
/// - `BankId` - Type-safe ID wrapper
/// - `DataConsentDto` - Data transfer object for DataConsent
/// - `DataConsentSummary` - Summary view of DataConsent
/// - `DataConsentId` - Type-safe ID wrapper
/// - `DataSubjectRequestDto` - Data transfer object for DataSubjectRequest
/// - `DataSubjectRequestSummary` - Summary view of DataSubjectRequest
/// - `DataSubjectRequestId` - Type-safe ID wrapper
/// - `EmployeeDto` - Data transfer object for Employee
/// - `EmployeeSummary` - Summary view of Employee
/// - `EmployeeId` - Type-safe ID wrapper
/// - `EmployeeBankAccountDto` - Data transfer object for EmployeeBankAccount
/// - `EmployeeBankAccountSummary` - Summary view of EmployeeBankAccount
/// - `EmployeeBankAccountId` - Type-safe ID wrapper
/// - `EmployeeBpjsDto` - Data transfer object for EmployeeBpjs
/// - `EmployeeBpjsSummary` - Summary view of EmployeeBpjs
/// - `EmployeeBpjsId` - Type-safe ID wrapper
/// - `EmployeeCertificationDto` - Data transfer object for EmployeeCertification
/// - `EmployeeCertificationSummary` - Summary view of EmployeeCertification
/// - `EmployeeCertificationId` - Type-safe ID wrapper
/// - `EmployeeContactDto` - Data transfer object for EmployeeContact
/// - `EmployeeContactSummary` - Summary view of EmployeeContact
/// - `EmployeeContactId` - Type-safe ID wrapper
/// - `EmployeeEducationDto` - Data transfer object for EmployeeEducation
/// - `EmployeeEducationSummary` - Summary view of EmployeeEducation
/// - `EmployeeEducationId` - Type-safe ID wrapper
/// - `EmployeeFamilyDto` - Data transfer object for EmployeeFamily
/// - `EmployeeFamilySummary` - Summary view of EmployeeFamily
/// - `EmployeeFamilyId` - Type-safe ID wrapper
/// - `EmployeeIdentityDto` - Data transfer object for EmployeeIdentity
/// - `EmployeeIdentitySummary` - Summary view of EmployeeIdentity
/// - `EmployeeIdentityId` - Type-safe ID wrapper
/// - `EmployeeTaxDto` - Data transfer object for EmployeeTax
/// - `EmployeeTaxSummary` - Summary view of EmployeeTax
/// - `EmployeeTaxId` - Type-safe ID wrapper
/// - `EmployeeWorkExperienceDto` - Data transfer object for EmployeeWorkExperience
/// - `EmployeeWorkExperienceSummary` - Summary view of EmployeeWorkExperience
/// - `EmployeeWorkExperienceId` - Type-safe ID wrapper
/// - `EmploymentDto` - Data transfer object for Employment
/// - `EmploymentSummary` - Summary view of Employment
/// - `EmploymentId` - Type-safe ID wrapper
/// - `EmploymentHistoryDto` - Data transfer object for EmploymentHistory
/// - `EmploymentHistorySummary` - Summary view of EmploymentHistory
/// - `EmploymentHistoryId` - Type-safe ID wrapper
/// - `PiiAccessLogDto` - Data transfer object for PiiAccessLog
/// - `PiiAccessLogSummary` - Summary view of PiiAccessLog
/// - `PiiAccessLogId` - Type-safe ID wrapper
/// - `ReligionDto` - Data transfer object for Religion
/// - `ReligionSummary` - Summary view of Religion
/// - `ReligionId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `BankCreatedEvent` - Published when Bank is created
/// - `BankUpdatedEvent` - Published when Bank is updated
/// - `BankDeletedEvent` - Published when Bank is deleted
/// - `DataConsentCreatedEvent` - Published when DataConsent is created
/// - `DataConsentUpdatedEvent` - Published when DataConsent is updated
/// - `DataConsentDeletedEvent` - Published when DataConsent is deleted
/// - `DataSubjectRequestCreatedEvent` - Published when DataSubjectRequest is created
/// - `DataSubjectRequestUpdatedEvent` - Published when DataSubjectRequest is updated
/// - `DataSubjectRequestDeletedEvent` - Published when DataSubjectRequest is deleted
/// - `EmployeeCreatedEvent` - Published when Employee is created
/// - `EmployeeUpdatedEvent` - Published when Employee is updated
/// - `EmployeeDeletedEvent` - Published when Employee is deleted
/// - `EmployeeBankAccountCreatedEvent` - Published when EmployeeBankAccount is created
/// - `EmployeeBankAccountUpdatedEvent` - Published when EmployeeBankAccount is updated
/// - `EmployeeBankAccountDeletedEvent` - Published when EmployeeBankAccount is deleted
/// - `EmployeeBpjsCreatedEvent` - Published when EmployeeBpjs is created
/// - `EmployeeBpjsUpdatedEvent` - Published when EmployeeBpjs is updated
/// - `EmployeeBpjsDeletedEvent` - Published when EmployeeBpjs is deleted
/// - `EmployeeCertificationCreatedEvent` - Published when EmployeeCertification is created
/// - `EmployeeCertificationUpdatedEvent` - Published when EmployeeCertification is updated
/// - `EmployeeCertificationDeletedEvent` - Published when EmployeeCertification is deleted
/// - `EmployeeContactCreatedEvent` - Published when EmployeeContact is created
/// - `EmployeeContactUpdatedEvent` - Published when EmployeeContact is updated
/// - `EmployeeContactDeletedEvent` - Published when EmployeeContact is deleted
/// - `EmployeeEducationCreatedEvent` - Published when EmployeeEducation is created
/// - `EmployeeEducationUpdatedEvent` - Published when EmployeeEducation is updated
/// - `EmployeeEducationDeletedEvent` - Published when EmployeeEducation is deleted
/// - `EmployeeFamilyCreatedEvent` - Published when EmployeeFamily is created
/// - `EmployeeFamilyUpdatedEvent` - Published when EmployeeFamily is updated
/// - `EmployeeFamilyDeletedEvent` - Published when EmployeeFamily is deleted
/// - `EmployeeIdentityCreatedEvent` - Published when EmployeeIdentity is created
/// - `EmployeeIdentityUpdatedEvent` - Published when EmployeeIdentity is updated
/// - `EmployeeIdentityDeletedEvent` - Published when EmployeeIdentity is deleted
/// - `EmployeeTaxCreatedEvent` - Published when EmployeeTax is created
/// - `EmployeeTaxUpdatedEvent` - Published when EmployeeTax is updated
/// - `EmployeeTaxDeletedEvent` - Published when EmployeeTax is deleted
/// - `EmployeeWorkExperienceCreatedEvent` - Published when EmployeeWorkExperience is created
/// - `EmployeeWorkExperienceUpdatedEvent` - Published when EmployeeWorkExperience is updated
/// - `EmployeeWorkExperienceDeletedEvent` - Published when EmployeeWorkExperience is deleted
/// - `EmploymentCreatedEvent` - Published when Employment is created
/// - `EmploymentUpdatedEvent` - Published when Employment is updated
/// - `EmploymentDeletedEvent` - Published when Employment is deleted
/// - `EmploymentHistoryCreatedEvent` - Published when EmploymentHistory is created
/// - `EmploymentHistoryUpdatedEvent` - Published when EmploymentHistory is updated
/// - `EmploymentHistoryDeletedEvent` - Published when EmploymentHistory is deleted
/// - `PiiAccessLogCreatedEvent` - Published when PiiAccessLog is created
/// - `PiiAccessLogUpdatedEvent` - Published when PiiAccessLog is updated
/// - `PiiAccessLogDeletedEvent` - Published when PiiAccessLog is deleted
/// - `ReligionCreatedEvent` - Published when Religion is created
/// - `ReligionUpdatedEvent` - Published when Religion is updated
/// - `ReligionDeletedEvent` - Published when Religion is deleted
pub struct ExportSummary;
