//! Public types for Employee module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// BANK TYPES
// ============================================================================

/// Type-safe ID for Bank
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BankId(pub Uuid);

impl BankId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BankId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BankId> for Uuid {
    fn from(id: BankId) -> Self {
        id.0
    }
}

/// Data transfer object for Bank
///
/// This is the public representation of Bank for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BankDto {
    pub id: BankId,
    pub name: String,
    pub code: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Bank for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BankSummary {
    pub id: BankId,
    pub name: String,
}

/// Reference to Bank for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BankRef {
    pub id: BankId,
}

// ============================================================================
// DATACONSENT TYPES
// ============================================================================

/// Type-safe ID for DataConsent
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DataConsentId(pub Uuid);

impl DataConsentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DataConsentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DataConsentId> for Uuid {
    fn from(id: DataConsentId) -> Self {
        id.0
    }
}

/// Data transfer object for DataConsent
///
/// This is the public representation of DataConsent for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataConsentDto {
    pub id: DataConsentId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub data_category: DataCategory,
    pub lawful_basis: LawfulBasis,
    pub consent_given_at: Option<DateTime<Utc>>,
    pub consent_method: Option<String>,
    pub privacy_notice_version: Option<String>,
    pub retention_until: Option<NaiveDate>,
    pub withdrawn_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of DataConsent for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataConsentSummary {
    pub id: DataConsentId,
}

/// Reference to DataConsent for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataConsentRef {
    pub id: DataConsentId,
}

// ============================================================================
// DATASUBJECTREQUEST TYPES
// ============================================================================

/// Type-safe ID for DataSubjectRequest
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DataSubjectRequestId(pub Uuid);

impl DataSubjectRequestId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DataSubjectRequestId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DataSubjectRequestId> for Uuid {
    fn from(id: DataSubjectRequestId) -> Self {
        id.0
    }
}

/// Data transfer object for DataSubjectRequest
///
/// This is the public representation of DataSubjectRequest for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataSubjectRequestDto {
    pub id: DataSubjectRequestId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub request_type: DataSubjectRight,
    pub status: DsarStatus,
    pub requested_at: DateTime<Utc>,
    pub fulfilled_at: Option<DateTime<Utc>>,
    pub response: Option<serde_json::Value>,
    pub note: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of DataSubjectRequest for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataSubjectRequestSummary {
    pub id: DataSubjectRequestId,
    pub status: DsarStatus,
}

/// Reference to DataSubjectRequest for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataSubjectRequestRef {
    pub id: DataSubjectRequestId,
}

// ============================================================================
// EMPLOYEE TYPES
// ============================================================================

/// Type-safe ID for Employee
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeId(pub Uuid);

impl EmployeeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeId> for Uuid {
    fn from(id: EmployeeId) -> Self {
        id.0
    }
}

/// Data transfer object for Employee
///
/// This is the public representation of Employee for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeDto {
    pub id: EmployeeId,
    pub company_id: Uuid,
    pub employee_number: String,
    pub user_id: Option<Uuid>,
    pub first_name: String,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub mobile_phone: Option<String>,
    pub phone: Option<String>,
    pub birth_place: Option<String>,
    pub birth_date: Option<NaiveDate>,
    pub gender: Option<Gender>,
    pub marital_status: Option<MaritalStatus>,
    pub blood_type: Option<BloodType>,
    pub religion_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Employee for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSummary {
    pub id: EmployeeId,
    pub first_name: String,
    pub last_name: Option<String>,
    pub email: Option<String>,
}

/// Reference to Employee for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeRef {
    pub id: EmployeeId,
}

// ============================================================================
// EMPLOYEEBANKACCOUNT TYPES
// ============================================================================

/// Type-safe ID for EmployeeBankAccount
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeBankAccountId(pub Uuid);

impl EmployeeBankAccountId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeBankAccountId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeBankAccountId> for Uuid {
    fn from(id: EmployeeBankAccountId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeBankAccount
///
/// This is the public representation of EmployeeBankAccount for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBankAccountDto {
    pub id: EmployeeBankAccountId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub bank_id: Uuid,
    pub account_number: String,
    pub account_name: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeBankAccount for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBankAccountSummary {
    pub id: EmployeeBankAccountId,
    pub account_name: Option<String>,
}

/// Reference to EmployeeBankAccount for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBankAccountRef {
    pub id: EmployeeBankAccountId,
}

// ============================================================================
// EMPLOYEEBPJS TYPES
// ============================================================================

/// Type-safe ID for EmployeeBpjs
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeBpjsId(pub Uuid);

impl EmployeeBpjsId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeBpjsId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeBpjsId> for Uuid {
    fn from(id: EmployeeBpjsId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeBpjs
///
/// This is the public representation of EmployeeBpjs for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBpjsDto {
    pub id: EmployeeBpjsId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub bpjs_ketenagakerjaan_number: Option<String>,
    pub npp_bpjs_ketenagakerjaan: Option<String>,
    pub bpjs_ketenagakerjaan_date: Option<NaiveDate>,
    pub bpjs_kesehatan_number: Option<String>,
    pub bpjs_kesehatan_family: Option<i32>,
    pub bpjs_kesehatan_date: Option<NaiveDate>,
    pub jaminan_pensiun_date: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeBpjs for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBpjsSummary {
    pub id: EmployeeBpjsId,
}

/// Reference to EmployeeBpjs for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeBpjsRef {
    pub id: EmployeeBpjsId,
}

// ============================================================================
// EMPLOYEECERTIFICATION TYPES
// ============================================================================

/// Type-safe ID for EmployeeCertification
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeCertificationId(pub Uuid);

impl EmployeeCertificationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeCertificationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeCertificationId> for Uuid {
    fn from(id: EmployeeCertificationId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeCertification
///
/// This is the public representation of EmployeeCertification for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCertificationDto {
    pub id: EmployeeCertificationId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub name: String,
    pub issuing_organization: Option<String>,
    pub start_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeCertification for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCertificationSummary {
    pub id: EmployeeCertificationId,
    pub name: String,
}

/// Reference to EmployeeCertification for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCertificationRef {
    pub id: EmployeeCertificationId,
}

// ============================================================================
// EMPLOYEECONTACT TYPES
// ============================================================================

/// Type-safe ID for EmployeeContact
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeContactId(pub Uuid);

impl EmployeeContactId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeContactId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeContactId> for Uuid {
    fn from(id: EmployeeContactId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeContact
///
/// This is the public representation of EmployeeContact for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeContactDto {
    pub id: EmployeeContactId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub name: String,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeContact for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeContactSummary {
    pub id: EmployeeContactId,
    pub name: String,
    pub email: Option<String>,
}

/// Reference to EmployeeContact for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeContactRef {
    pub id: EmployeeContactId,
}

// ============================================================================
// EMPLOYEEEDUCATION TYPES
// ============================================================================

/// Type-safe ID for EmployeeEducation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeEducationId(pub Uuid);

impl EmployeeEducationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeEducationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeEducationId> for Uuid {
    fn from(id: EmployeeEducationId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeEducation
///
/// This is the public representation of EmployeeEducation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeEducationDto {
    pub id: EmployeeEducationId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub institution_name: String,
    pub major: Option<String>,
    pub field: Option<String>,
    pub score: Option<Decimal>,
    pub start_year: Option<i32>,
    pub end_year: Option<i32>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeEducation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeEducationSummary {
    pub id: EmployeeEducationId,
    pub institution_name: String,
}

/// Reference to EmployeeEducation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeEducationRef {
    pub id: EmployeeEducationId,
}

// ============================================================================
// EMPLOYEEFAMILY TYPES
// ============================================================================

/// Type-safe ID for EmployeeFamily
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeFamilyId(pub Uuid);

impl EmployeeFamilyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeFamilyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeFamilyId> for Uuid {
    fn from(id: EmployeeFamilyId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeFamily
///
/// This is the public representation of EmployeeFamily for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeFamilyDto {
    pub id: EmployeeFamilyId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub name: String,
    pub relationship: FamilyRelationship,
    pub birth_date: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeFamily for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeFamilySummary {
    pub id: EmployeeFamilyId,
    pub name: String,
}

/// Reference to EmployeeFamily for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeFamilyRef {
    pub id: EmployeeFamilyId,
}

// ============================================================================
// EMPLOYEEIDENTITY TYPES
// ============================================================================

/// Type-safe ID for EmployeeIdentity
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeIdentityId(pub Uuid);

impl EmployeeIdentityId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeIdentityId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeIdentityId> for Uuid {
    fn from(id: EmployeeIdentityId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeIdentity
///
/// This is the public representation of EmployeeIdentity for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeIdentityDto {
    pub id: EmployeeIdentityId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub identity_type: IdentityType,
    pub identity_number: String,
    pub identity_expiry_date: Option<NaiveDate>,
    pub is_permanent: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeIdentity for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeIdentitySummary {
    pub id: EmployeeIdentityId,
}

/// Reference to EmployeeIdentity for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeIdentityRef {
    pub id: EmployeeIdentityId,
}

// ============================================================================
// EMPLOYEETAX TYPES
// ============================================================================

/// Type-safe ID for EmployeeTax
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeTaxId(pub Uuid);

impl EmployeeTaxId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeTaxId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeTaxId> for Uuid {
    fn from(id: EmployeeTaxId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeTax
///
/// This is the public representation of EmployeeTax for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeTaxDto {
    pub id: EmployeeTaxId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub npwp_number: Option<String>,
    pub ptkp_override: Option<PtkpTier>,
    pub tax_method: TaxMethod,
    pub tax_salary: TaxSalary,
    pub taxable_date: Option<NaiveDate>,
    pub beginning_netto: Option<Decimal>,
    pub pph21_paid: Option<Decimal>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeTax for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeTaxSummary {
    pub id: EmployeeTaxId,
}

/// Reference to EmployeeTax for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeTaxRef {
    pub id: EmployeeTaxId,
}

// ============================================================================
// EMPLOYEEWORKEXPERIENCE TYPES
// ============================================================================

/// Type-safe ID for EmployeeWorkExperience
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeWorkExperienceId(pub Uuid);

impl EmployeeWorkExperienceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeWorkExperienceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeWorkExperienceId> for Uuid {
    fn from(id: EmployeeWorkExperienceId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeWorkExperience
///
/// This is the public representation of EmployeeWorkExperience for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeWorkExperienceDto {
    pub id: EmployeeWorkExperienceId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub company_name: String,
    pub job_position: Option<String>,
    pub start_date: Option<NaiveDate>,
    pub end_date: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeWorkExperience for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeWorkExperienceSummary {
    pub id: EmployeeWorkExperienceId,
    pub company_name: String,
}

/// Reference to EmployeeWorkExperience for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeWorkExperienceRef {
    pub id: EmployeeWorkExperienceId,
}

// ============================================================================
// EMPLOYMENT TYPES
// ============================================================================

/// Type-safe ID for Employment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmploymentId(pub Uuid);

impl EmploymentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmploymentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmploymentId> for Uuid {
    fn from(id: EmploymentId) -> Self {
        id.0
    }
}

/// Data transfer object for Employment
///
/// This is the public representation of Employment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentDto {
    pub id: EmploymentId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub employment_status: EmploymentStatus,
    pub join_date: NaiveDate,
    pub end_join_date: Option<NaiveDate>,
    pub department_id: Option<Uuid>,
    pub level_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    pub direct_manager_id: Option<Uuid>,
    pub status: EmploymentState,
    pub metadata: serde_json::Value,
}

/// Summary view of Employment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentSummary {
    pub id: EmploymentId,
    pub status: EmploymentState,
}

/// Reference to Employment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentRef {
    pub id: EmploymentId,
}

// ============================================================================
// EMPLOYMENTHISTORY TYPES
// ============================================================================

/// Type-safe ID for EmploymentHistory
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmploymentHistoryId(pub Uuid);

impl EmploymentHistoryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmploymentHistoryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmploymentHistoryId> for Uuid {
    fn from(id: EmploymentHistoryId) -> Self {
        id.0
    }
}

/// Data transfer object for EmploymentHistory
///
/// This is the public representation of EmploymentHistory for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentHistoryDto {
    pub id: EmploymentHistoryId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub effective_date: NaiveDate,
    pub action: EmploymentAction,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub reference_id: Option<Uuid>,
    pub note: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmploymentHistory for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentHistorySummary {
    pub id: EmploymentHistoryId,
}

/// Reference to EmploymentHistory for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmploymentHistoryRef {
    pub id: EmploymentHistoryId,
}

// ============================================================================
// PIIACCESSLOG TYPES
// ============================================================================

/// Type-safe ID for PiiAccessLog
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PiiAccessLogId(pub Uuid);

impl PiiAccessLogId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PiiAccessLogId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PiiAccessLogId> for Uuid {
    fn from(id: PiiAccessLogId) -> Self {
        id.0
    }
}

/// Data transfer object for PiiAccessLog
///
/// This is the public representation of PiiAccessLog for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PiiAccessLogDto {
    pub id: PiiAccessLogId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub accessed_by: Uuid,
    pub data_category: DataCategory,
    pub purpose: Option<String>,
    pub accessed_at: DateTime<Utc>,
}

/// Summary view of PiiAccessLog for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PiiAccessLogSummary {
    pub id: PiiAccessLogId,
}

/// Reference to PiiAccessLog for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PiiAccessLogRef {
    pub id: PiiAccessLogId,
}

// ============================================================================
// RELIGION TYPES
// ============================================================================

/// Type-safe ID for Religion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ReligionId(pub Uuid);

impl ReligionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ReligionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ReligionId> for Uuid {
    fn from(id: ReligionId) -> Self {
        id.0
    }
}

/// Data transfer object for Religion
///
/// This is the public representation of Religion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReligionDto {
    pub id: ReligionId,
    pub name: String,
    pub metadata: serde_json::Value,
}

/// Summary view of Religion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReligionSummary {
    pub id: ReligionId,
    pub name: String,
}

/// Reference to Religion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReligionRef {
    pub id: ReligionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here

/// The Indonesia statutory inputs payroll needs to compute net pay (PPh 21, BPJS Kesehatan,
/// BPJS Ketenagakerjaan, THR) for one employee. Read via [`super::services::EmployeeQueryService::statutory_inputs`].
///
/// `base_salary` is intentionally NOT here: the employee module stores no queryable monthly salary
/// (`EmployeeTax.tax_salary` is a Taxable/NonTaxable flag, not an amount, and there is no
/// CompensationChange entity yet). Payroll supplies the structure's monthly gross as the statutory
/// base when it calls `compute_statutory` — that is the salary actually being paid this run.
///
/// `join_date` is optional because an employee may legally exist without an employment row yet
/// (newly onboarded); a `None` means "tenure unknown" and payroll's THR calc yields zero (no THR).
#[derive(Debug, Clone)]
pub struct StatutoryInputs {
    /// PTKP tier (override wins, else derived from dependents) — drives PPh 21 relief.
    pub ptkp: PtkpTier,
    /// Whether the employee has an NPWP (non-empty `npwp_number`). Drives the 20% PPh 21 surtax
    /// when false.
    pub has_npwp: bool,
    /// BPJS Kesehatan registered family size (`bpjs_kesehatan_family`). Currently informational —
    /// the employee share is 1% of capped salary regardless of family size; the employer share
    /// scales with it (not modeled in the employee-side deduction).
    pub bpjs_kesehatan_family: Option<i32>,
    /// Employment join date — the anchor for THR tenure pro-rating. `None` when no employment row.
    pub join_date: Option<NaiveDate>,
}
// <<< CUSTOM TYPES END >>>
