//! Use case type aliases for EmployeeIdentity aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeIdentityDto, UpdateEmployeeIdentityDto};
use crate::application::service::EmployeeIdentityService;
use crate::domain::entity::EmployeeIdentity;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeIdentityUseCase = CreateUseCase<EmployeeIdentity, CreateEmployeeIdentityDto, EmployeeIdentityService>;
pub type UpdateEmployeeIdentityUseCase = UpdateUseCase<EmployeeIdentity, UpdateEmployeeIdentityDto, EmployeeIdentityService>;
pub type GetEmployeeIdentityUseCase    = GetUseCase<EmployeeIdentity, EmployeeIdentityService>;
pub type DeleteEmployeeIdentityUseCase = DeleteUseCase<EmployeeIdentity, EmployeeIdentityService>;
pub type ListEmployeeIdentityUseCase   = ListUseCase<EmployeeIdentity, EmployeeIdentityService>;

// <<< CUSTOM
// END CUSTOM
