//! Use case type aliases for EmployeeContact aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeContactDto, UpdateEmployeeContactDto};
use crate::application::service::EmployeeContactService;
use crate::domain::entity::EmployeeContact;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeContactUseCase = CreateUseCase<EmployeeContact, CreateEmployeeContactDto, EmployeeContactService>;
pub type UpdateEmployeeContactUseCase = UpdateUseCase<EmployeeContact, UpdateEmployeeContactDto, EmployeeContactService>;
pub type GetEmployeeContactUseCase    = GetUseCase<EmployeeContact, EmployeeContactService>;
pub type DeleteEmployeeContactUseCase = DeleteUseCase<EmployeeContact, EmployeeContactService>;
pub type ListEmployeeContactUseCase   = ListUseCase<EmployeeContact, EmployeeContactService>;

// <<< CUSTOM
// END CUSTOM
