//! Use case type aliases for EmployeeBankAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeBankAccountDto, UpdateEmployeeBankAccountDto};
use crate::application::service::EmployeeBankAccountService;
use crate::domain::entity::EmployeeBankAccount;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeBankAccountUseCase = CreateUseCase<EmployeeBankAccount, CreateEmployeeBankAccountDto, EmployeeBankAccountService>;
pub type UpdateEmployeeBankAccountUseCase = UpdateUseCase<EmployeeBankAccount, UpdateEmployeeBankAccountDto, EmployeeBankAccountService>;
pub type GetEmployeeBankAccountUseCase    = GetUseCase<EmployeeBankAccount, EmployeeBankAccountService>;
pub type DeleteEmployeeBankAccountUseCase = DeleteUseCase<EmployeeBankAccount, EmployeeBankAccountService>;
pub type ListEmployeeBankAccountUseCase   = ListUseCase<EmployeeBankAccount, EmployeeBankAccountService>;

// <<< CUSTOM
// END CUSTOM
