//! Use case type aliases for EmployeeEducation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeEducationDto, UpdateEmployeeEducationDto};
use crate::application::service::EmployeeEducationService;
use crate::domain::entity::EmployeeEducation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeEducationUseCase = CreateUseCase<EmployeeEducation, CreateEmployeeEducationDto, EmployeeEducationService>;
pub type UpdateEmployeeEducationUseCase = UpdateUseCase<EmployeeEducation, UpdateEmployeeEducationDto, EmployeeEducationService>;
pub type GetEmployeeEducationUseCase    = GetUseCase<EmployeeEducation, EmployeeEducationService>;
pub type DeleteEmployeeEducationUseCase = DeleteUseCase<EmployeeEducation, EmployeeEducationService>;
pub type ListEmployeeEducationUseCase   = ListUseCase<EmployeeEducation, EmployeeEducationService>;

// <<< CUSTOM
// END CUSTOM
