//! Use case type aliases for EmploymentHistory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmploymentHistoryDto, UpdateEmploymentHistoryDto};
use crate::application::service::EmploymentHistoryService;
use crate::domain::entity::EmploymentHistory;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmploymentHistoryUseCase = CreateUseCase<EmploymentHistory, CreateEmploymentHistoryDto, EmploymentHistoryService>;
pub type UpdateEmploymentHistoryUseCase = UpdateUseCase<EmploymentHistory, UpdateEmploymentHistoryDto, EmploymentHistoryService>;
pub type GetEmploymentHistoryUseCase    = GetUseCase<EmploymentHistory, EmploymentHistoryService>;
pub type DeleteEmploymentHistoryUseCase = DeleteUseCase<EmploymentHistory, EmploymentHistoryService>;
pub type ListEmploymentHistoryUseCase   = ListUseCase<EmploymentHistory, EmploymentHistoryService>;

// <<< CUSTOM
// END CUSTOM
