//! Use case type aliases for EmployeeFamily aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeFamilyDto, UpdateEmployeeFamilyDto};
use crate::application::service::EmployeeFamilyService;
use crate::domain::entity::EmployeeFamily;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeFamilyUseCase = CreateUseCase<EmployeeFamily, CreateEmployeeFamilyDto, EmployeeFamilyService>;
pub type UpdateEmployeeFamilyUseCase = UpdateUseCase<EmployeeFamily, UpdateEmployeeFamilyDto, EmployeeFamilyService>;
pub type GetEmployeeFamilyUseCase    = GetUseCase<EmployeeFamily, EmployeeFamilyService>;
pub type DeleteEmployeeFamilyUseCase = DeleteUseCase<EmployeeFamily, EmployeeFamilyService>;
pub type ListEmployeeFamilyUseCase   = ListUseCase<EmployeeFamily, EmployeeFamilyService>;

// <<< CUSTOM
// END CUSTOM
