//! Use case type aliases for Example aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateExampleDto, UpdateExampleDto};
use crate::application::service::ExampleService;
use crate::domain::entity::Example;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateExampleUseCase = CreateUseCase<Example, CreateExampleDto, ExampleService>;
pub type UpdateExampleUseCase = UpdateUseCase<Example, UpdateExampleDto, ExampleService>;
pub type GetExampleUseCase    = GetUseCase<Example, ExampleService>;
pub type DeleteExampleUseCase = DeleteUseCase<Example, ExampleService>;
pub type ListExampleUseCase   = ListUseCase<Example, ExampleService>;

// <<< CUSTOM
// END CUSTOM
