//! Use case type aliases for PiiAccessLog aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePiiAccessLogDto, UpdatePiiAccessLogDto};
use crate::application::service::PiiAccessLogService;
use crate::domain::entity::PiiAccessLog;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePiiAccessLogUseCase = CreateUseCase<PiiAccessLog, CreatePiiAccessLogDto, PiiAccessLogService>;
pub type UpdatePiiAccessLogUseCase = UpdateUseCase<PiiAccessLog, UpdatePiiAccessLogDto, PiiAccessLogService>;
pub type GetPiiAccessLogUseCase    = GetUseCase<PiiAccessLog, PiiAccessLogService>;
pub type DeletePiiAccessLogUseCase = DeleteUseCase<PiiAccessLog, PiiAccessLogService>;
pub type ListPiiAccessLogUseCase   = ListUseCase<PiiAccessLog, PiiAccessLogService>;

// <<< CUSTOM
// END CUSTOM
