//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod bank_handler;
pub mod data_consent_handler;
pub mod data_subject_request_handler;
pub mod employee_handler;
pub mod employee_bank_account_handler;
pub mod employee_bpjs_handler;
pub mod employee_certification_handler;
pub mod employee_contact_handler;
pub mod employee_education_handler;
pub mod employee_family_handler;
pub mod employee_identity_handler;
pub mod employee_tax_handler;
pub mod employee_work_experience_handler;
pub mod employment_handler;
pub mod employment_history_handler;
pub mod pii_access_log_handler;
pub mod religion_handler;

// <<< CUSTOM
pub mod employee_public_handler;
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use bank_handler::{create_bank_routes, create_bank_read_routes, create_bank_write_routes};
pub use data_consent_handler::{create_data_consent_routes, create_data_consent_read_routes, create_data_consent_write_routes};
pub use data_subject_request_handler::{create_data_subject_request_routes, create_data_subject_request_read_routes, create_data_subject_request_write_routes};
pub use employee_handler::{create_employee_routes, create_employee_read_routes, create_employee_write_routes};
pub use employee_bank_account_handler::{create_employee_bank_account_routes, create_employee_bank_account_read_routes, create_employee_bank_account_write_routes};
pub use employee_bpjs_handler::{create_employee_bpjs_routes, create_employee_bpjs_read_routes, create_employee_bpjs_write_routes};
pub use employee_certification_handler::{create_employee_certification_routes, create_employee_certification_read_routes, create_employee_certification_write_routes};
pub use employee_contact_handler::{create_employee_contact_routes, create_employee_contact_read_routes, create_employee_contact_write_routes};
pub use employee_education_handler::{create_employee_education_routes, create_employee_education_read_routes, create_employee_education_write_routes};
pub use employee_family_handler::{create_employee_family_routes, create_employee_family_read_routes, create_employee_family_write_routes};
pub use employee_identity_handler::{create_employee_identity_routes, create_employee_identity_read_routes, create_employee_identity_write_routes};
pub use employee_tax_handler::{create_employee_tax_routes, create_employee_tax_read_routes, create_employee_tax_write_routes};
pub use employee_work_experience_handler::{create_employee_work_experience_routes, create_employee_work_experience_read_routes, create_employee_work_experience_write_routes};
pub use employment_handler::{create_employment_routes, create_employment_read_routes, create_employment_write_routes};
pub use employment_history_handler::{create_employment_history_routes, create_employment_history_read_routes, create_employment_history_write_routes};
pub use pii_access_log_handler::{create_pii_access_log_routes, create_pii_access_log_read_routes, create_pii_access_log_write_routes};
pub use religion_handler::{create_religion_routes, create_religion_read_routes, create_religion_write_routes};
// <<< CUSTOM
pub use employee_public_handler::create_employee_public_read_routes;
// END CUSTOM
